import { createSeededRandom, getDailySeed } from '../dailyRotation';
import { EarlyPuzzleQuestion } from './earlyPuzzle';

export type ElementaryPuzzleLevel = 3 | 4;

const PHASES = ['Look carefully', 'Name the rule', 'Compare', 'Use the clues', 'Try a strategy', 'Explain'];

const shuffle = <T,>(items: T[], random: () => number): T[] => {
  const copy = [...items];
  for (let index = copy.length - 1; index > 0; index -= 1) {
    const swapIndex = Math.floor(random() * (index + 1));
    [copy[index], copy[swapIndex]] = [copy[swapIndex], copy[index]];
  }
  return copy;
};

const choices = (answer: string, distractors: string[], random: () => number): string[] => (
  shuffle([answer, ...shuffle([...new Set(distractors)].filter(item => item !== answer), random).slice(0, 3)], random)
);

type QuestionSeed = Omit<EarlyPuzzleQuestion, 'id' | 'phase'>;

const firstGradeFactories = (random: () => number): Array<() => QuestionSeed> => [
  () => ({ title: 'Count-On Pattern', prompt: 'What number comes next?', visual: 'pattern', clueItems: ['2', '4', '6', '?'], clueText: 'Add 2 each time', answer: '8', options: choices('8', ['7', '9', '10', '12'], random), skill: 'extending a count-by-two pattern', explanation: 'Each number is 2 more than the number before it: 2, 4, 6, 8.' }),
  () => ({ title: 'Count-by-Fives', prompt: 'Which number completes the pattern?', visual: 'pattern', clueItems: ['5', '10', '15', '?'], clueText: 'The numbers grow by 5', answer: '20', options: choices('20', ['16', '18', '25', '30'], random), skill: 'extending a count-by-five pattern', explanation: 'Adding 5 to 15 gives 20, so 20 is the next number in the pattern.' }),
  () => ({ title: 'Shape Cycle', prompt: 'Which shape comes next in the repeating rule?', visual: 'pattern', clueItems: ['circle', 'square', 'triangle', 'circle', 'square', '?'], clueText: 'Circle, square, triangle repeats', answer: 'triangle', options: choices('triangle', ['circle', 'square', 'diamond', 'star'], random), skill: 'tracking a three-part visual pattern', explanation: 'The repeating unit is circle, square, triangle, so triangle completes the second unit.' }),
  () => ({ title: 'Word Relationship', prompt: 'A bird lives in a nest. A bee lives in a ...', visual: 'logic', clueItems: ['bird', 'nest', 'bee', '?'], clueText: 'Animal goes with its home', answer: 'hive', options: choices('hive', ['pond', 'stable', 'web', 'den'], random), skill: 'solving a word analogy', explanation: 'A nest is a bird home, and a hive is a bee home, so the relationships match.' }),
  () => ({ title: 'Find the Shared Rule', prompt: 'What is true about every item in the group?', visual: 'sort', clueItems: ['circle', 'square', 'triangle'], clueText: 'Compare all three figures', answer: 'They are closed shapes', options: choices('They are closed shapes', ['They all have four sides', 'They are all circles', 'They are all numbers', 'They all have six corners'], random), skill: 'identifying a shared attribute', explanation: 'Every outline closes all the way around, even though the shapes have different sides and corners.' }),
  () => ({ title: 'Put Events in Order', prompt: 'Which event should happen second?', visual: 'logic', clueItems: ['get ready', 'travel', 'arrive'], clueText: 'First get ready, next travel, last arrive', answer: 'travel', options: choices('travel', ['arrive', 'sleep', 'celebrate', 'get ready'], random), skill: 'sequencing events logically', explanation: 'After getting ready, you travel. Arriving happens only after the travel step.' }),
  () => ({ title: 'Position Detective', prompt: 'Which letter is immediately between A and C?', visual: 'position', clueItems: ['A', 'B', 'C', 'D'], clueText: 'Read the row from left to right', answer: 'B', options: choices('B', ['A', 'C', 'D', 'E'], random), skill: 'using relative position', explanation: 'B is directly after A and directly before C, so it is between them.' }),
  () => ({ title: 'Category Detective', prompt: 'Which word does not belong with the fruits?', visual: 'odd-one-out', clueItems: ['apple', 'banana', 'carrot', 'pear'], clueText: 'Three fruits and one vegetable', answer: 'carrot', options: choices('carrot', ['apple', 'banana', 'pear', 'grape'], random), skill: 'classifying and finding an exception', explanation: 'A carrot is a vegetable. Apple, banana, and pear are fruits.' }),
  () => ({ title: 'Mirror Match', prompt: 'Which shape can be folded in half to make matching left and right sides?', visual: 'shape', clueItems: ['heart'], clueText: 'Imagine a line down the middle', answer: 'heart', options: choices('heart', ['uneven scribble', 'open curve', 'zigzag', 'random dots'], random), skill: 'recognizing line symmetry', explanation: 'A balanced heart has matching left and right halves across a vertical line of symmetry.' }),
  () => ({ title: 'Function Machine', prompt: 'The machine adds 3. What comes out when 6 goes in?', visual: 'logic', clueItems: ['6', '+3', '?'], clueText: 'Input 6, apply the rule, find the output', answer: '9', options: choices('9', ['3', '6', '8', '12'], random), skill: 'applying a one-step function rule', explanation: 'The rule says add 3, and 6 plus 3 equals 9.' }),
  () => ({ title: 'Use Every Clue', prompt: 'Choose the object that is blue and has four equal sides.', visual: 'logic', clueItems: ['blue', '4 equal sides'], clueText: 'Both clues must be true', answer: 'blue square', options: choices('blue square', ['red square', 'blue triangle', 'blue circle', 'green rectangle'], random), skill: 'eliminating choices with two attributes', explanation: 'Blue square is the only choice that is blue and also has four equal sides.' }),
  () => ({ title: 'Symbol Code', prompt: 'If A means 1, B means 2, and C means 3, what does B mean?', visual: 'memory', clueItems: ['A=1', 'B=2', 'C=3'], clueText: 'Use the code key', answer: '2', options: choices('2', ['1', '3', '4', 'B'], random), skill: 'reading a simple symbol code', explanation: 'The key directly pairs B with the number 2.' }),
];

const secondGradeFactories = (random: () => number): Array<() => QuestionSeed> => [
  () => ({ title: 'Two-Rule Pattern', prompt: 'What number comes next?', visual: 'pattern', clueItems: ['2', '4', '5', '10', '11', '?'], clueText: 'Multiply by 2, then add 1; repeat', answer: '22', options: choices('22', ['12', '20', '21', '23'], random), skill: 'extending a two-rule number pattern', explanation: 'After 10, the rule adds 1 to make 11. The next rule doubles 11 to make 22.' }),
  () => ({ title: 'Multiply Machine', prompt: 'The machine doubles every input. What comes out when 4 goes in?', visual: 'logic', clueItems: ['4', 'x2', '?'], clueText: 'Use the same rule on every input', answer: '8', options: choices('8', ['2', '4', '6', '12'], random), skill: 'applying a multiplication function rule', explanation: 'Doubling means multiplying by 2, and 4 times 2 equals 8.' }),
  () => ({ title: 'Line-Up Logic', prompt: 'Kai is first. Luna is after Kai but before Mia. Who is in the middle?', visual: 'position', clueItems: ['Kai', '?', 'Mia'], clueText: 'Kai before Luna before Mia', answer: 'Luna', options: choices('Luna', ['Kai', 'Mia', 'Noah', 'Everyone'], random), skill: 'deducing order from relational clues', explanation: 'Luna must come after Kai and before Mia, placing Luna in the middle.' }),
  () => ({ title: 'Coordinate Move', prompt: 'Start at (1, 1). Move right 2 and up 1. Where do you land?', visual: 'position', clueItems: ['(1,1)', 'right 2', 'up 1', '?'], clueText: 'Right changes the first number; up changes the second', answer: '(3, 2)', options: choices('(3, 2)', ['(2, 3)', '(3, 1)', '(1, 3)', '(2, 2)'], random), skill: 'tracking movement on a coordinate grid', explanation: 'Moving right 2 changes x from 1 to 3. Moving up 1 changes y from 1 to 2.' }),
  () => ({ title: 'Quarter Turn', prompt: 'An arrow points up. After one quarter turn clockwise, where does it point?', visual: 'position', clueItems: ['up', 'clockwise', '?'], clueText: 'Make one 90-degree turn to the right', answer: 'right', options: choices('right', ['left', 'down', 'up', 'both ways'], random), skill: 'visualizing a quarter rotation', explanation: 'A clockwise quarter turn moves an upward arrow 90 degrees so it points right.' }),
  () => ({ title: 'Category Intersection', prompt: 'Which animal belongs in both groups: mammals and animals that fly?', visual: 'sort', clueItems: ['mammal', 'flies'], clueText: 'The answer must fit both groups', answer: 'bat', options: choices('bat', ['eagle', 'whale', 'butterfly', 'penguin'], random), skill: 'finding the intersection of categories', explanation: 'A bat is a mammal and it can fly, so it belongs in both groups.' }),
  () => ({ title: 'Number Constraints', prompt: 'Which number is even, greater than 20, less than 30, and a multiple of 3?', visual: 'logic', clueItems: ['even', '>20', '<30', 'x3'], clueText: 'Check every condition', answer: '24', options: choices('24', ['21', '25', '28', '30'], random), skill: 'solving with multiple constraints', explanation: '24 is even, lies between 20 and 30, and equals 3 times 8. It satisfies every clue.' }),
  () => ({ title: 'Crack the Code', prompt: 'Use A=1, B=2, and so on. What is C + A + T?', visual: 'logic', clueItems: ['C=3', 'A=1', 'T=20'], clueText: 'Add the three letter values', answer: '24', options: choices('24', ['21', '23', '25', '31'], random), skill: 'decoding and combining symbol values', explanation: 'C is 3, A is 1, and T is 20. Adding 3 + 1 + 20 gives 24.' }),
  () => ({ title: 'Relationship Match', prompt: 'An hour is measured on a clock. A day is tracked on a ...', visual: 'logic', clueItems: ['hour', 'clock', 'day', '?'], clueText: 'Match each time unit to its tool', answer: 'calendar', options: choices('calendar', ['ruler', 'thermometer', 'scale', 'compass'], random), skill: 'solving a functional analogy', explanation: 'A clock tracks hours, while a calendar tracks days, so the relationships match.' }),
  () => ({ title: 'Shape Deduction', prompt: 'I have four equal sides and four right angles. What shape am I?', visual: 'shape', clueItems: ['4 equal sides', '4 right angles'], clueText: 'Use both shape attributes', answer: 'square', options: choices('square', ['rectangle', 'triangle', 'circle', 'pentagon'], random), skill: 'deducing a shape from attributes', explanation: 'A square has exactly four equal sides and four right angles.' }),
  () => ({ title: 'Growing Differences', prompt: 'What number comes next: 1, 2, 4, 7, 11, ...?', visual: 'pattern', clueItems: ['1', '2', '4', '7', '11', '?'], clueText: 'Add 1, then 2, then 3, then 4', answer: '16', options: choices('16', ['12', '14', '15', '22'], random), skill: 'tracking growing differences', explanation: 'The added amount grows by 1 each time. After adding 4 to get 11, add 5 to get 16.' }),
  () => ({ title: 'Choose a Strategy', prompt: 'What is the best first step for a puzzle with many directions?', visual: 'logic', clueItems: ['read', 'plan', 'solve', 'check'], clueText: 'Use an organized process', answer: 'Break it into smaller steps', options: choices('Break it into smaller steps', ['Guess without reading', 'Skip every clue', 'Change all the rules', 'Choose the longest answer'], random), skill: 'selecting a multi-step problem-solving strategy', explanation: 'Breaking a complex task into smaller steps makes each direction easier to follow and check.' }),
];

export const generateElementaryPuzzleQuestion = (level: ElementaryPuzzleLevel, step: number): EarlyPuzzleQuestion => {
  const random = createSeededRandom(getDailySeed(`elementary-puzzle-grade-${level}`, step));
  const factories = level === 3 ? firstGradeFactories(random) : secondGradeFactories(random);
  const question = factories[step % factories.length]();
  return { ...question, id: `elementary-puzzle-${level}-${step}-${question.skill.replace(/[^a-z0-9]+/gi, '-').toLowerCase()}`, phase: PHASES[step % PHASES.length] };
};
