import { createSeededRandom, getDailySeed } from '../dailyRotation';
import { EarlyMusicQuestion } from './earlyMusic';

export type ElementaryMusicLevel = 3 | 4;

const PHASES = ['Listen', 'Move to the beat', 'Compare sounds', 'Echo', 'Build a pattern', 'Music check'];

const shuffle = <T,>(items: T[], random: () => number): T[] => {
  const copy = [...items];
  for (let index = copy.length - 1; index > 0; index -= 1) {
    const swapIndex = Math.floor(random() * (index + 1));
    [copy[index], copy[swapIndex]] = [copy[swapIndex], copy[index]];
  }
  return copy;
};

const choices = (answer: string, distractors: string[], random: () => number): string[] => (
  shuffle([answer, ...shuffle([...new Set(distractors)].filter(item => item !== answer), random).slice(0, 3)], random)
);

type QuestionSeed = Omit<EarlyMusicQuestion, 'id' | 'phase'>;

const firstGradeFactories = (random: () => number): Array<() => QuestionSeed> => [
  () => ({ title: 'Pitch Steps', prompt: 'How does the melody move?', visual: 'melody', musicClue: 'C, D, E, F', sampleNotes: [262, 294, 330, 349], sampleGapMs: 380, answer: 'Up by steps', options: choices('Up by steps', ['Down by steps', 'One repeated pitch', 'Only rests', 'Up by a large leap'], random), skill: 'ascending stepwise melody', explanation: 'Each pitch is a little higher than the one before, so the melody moves up by steps.' }),
  () => ({ title: 'Descending Line', prompt: 'Which direction does this melody travel?', visual: 'melody', musicClue: 'G, F, E, D', sampleNotes: [392, 349, 330, 294], sampleGapMs: 380, answer: 'Down by steps', options: choices('Down by steps', ['Up by steps', 'The same note', 'Only silence', 'A faster tempo'], random), skill: 'descending stepwise melody', explanation: 'Each note is slightly lower than the previous note, creating a descending line.' }),
  () => ({ title: 'Melody Arch', prompt: 'What shape does the melody make?', visual: 'melody', musicClue: 'Low, middle, high, middle, low', sampleNotes: [262, 330, 392, 330, 262], sampleGapMs: 360, answer: 'Up and then down', options: choices('Up and then down', ['Down only', 'One repeated pitch', 'Silence only', 'Fast and then slow'], random), skill: 'melodic contour', explanation: 'The pitches rise to a high point and then return downward, forming an arch.' }),
  () => {
    const fast = random() > 0.5;
    return { title: 'Tempo Choice', prompt: 'Which tempo word best describes the sample?', visual: 'tempo', musicClue: fast ? 'Quick steady pulse' : 'Calm steady pulse', sampleNotes: [330, 330, 330, 330, 330], sampleGapMs: fast ? 190 : 620, answer: fast ? 'Fast' : 'Slow', options: choices(fast ? 'Fast' : 'Slow', ['Fast', 'Slow', 'High', 'Low', 'Silent'], random), skill: 'identifying tempo', explanation: `${fast ? 'Fast' : 'Slow'} describes how quickly the steady beats occur.` };
  },
  () => ({ title: 'Count a Measure', prompt: 'How many steady beats are in the sample?', visual: 'beats', musicClue: 'One measure with four equal beats', sampleNotes: [294, 294, 294, 294], sampleGapMs: 420, answer: '4', options: choices('4', ['2', '3', '5', '6'], random), skill: 'counting beats in a measure', explanation: 'The sample contains four evenly spaced beats, so the measure has four beats.' }),
  () => ({ title: 'Quarter Rest', prompt: 'Which rhythm matches what you hear?', visual: 'rest', musicClue: 'Sound, sound, rest, sound', sampleNotes: [330, 330, 0, 330], sampleGapMs: 400, answer: 'Ta, ta, rest, ta', options: choices('Ta, ta, rest, ta', ['Ta, rest, ta, ta', 'Rest, ta, ta, ta', 'Ta, ta, ta, ta', 'Rest, rest, ta, ta'], random), skill: 'quarter notes and rests', explanation: 'Two sounds are followed by one silent beat and one final sound.' }),
  () => ({ title: 'Rhythm Echo', prompt: 'Which rhythm copies the sample exactly?', visual: 'echo', musicClue: 'Sound, rest, sound, sound', sampleNotes: [349, 0, 349, 349], sampleGapMs: 370, answer: 'Clap, rest, clap, clap', options: choices('Clap, rest, clap, clap', ['Clap, clap, rest, clap', 'Rest, clap, clap, clap', 'Clap, rest, rest, clap', 'Four rests'], random), skill: 'echoing four-beat rhythms', explanation: 'An exact echo keeps every sound and rest in the same four-beat order.' }),
  () => ({ title: 'Pitch Pattern', prompt: 'What comes next in the pitch pattern?', visual: 'rhythm', musicClue: 'Low, low, high, low, low, ?', sampleNotes: [220, 220, 440, 220, 220], sampleGapMs: 340, answer: 'High', options: choices('High', ['Low', 'Rest', 'Faster', 'Slower'], random), skill: 'continuing pitch patterns', explanation: 'The repeating unit is low, low, high, so high completes the second unit.' }),
  () => ({ title: 'Same Musical Phrase', prompt: 'Do the two short phrases match?', visual: 'compare', musicClue: 'C-E-G | C-E-G', sampleNotes: [262, 330, 392, 0, 262, 330, 392], sampleGapMs: 320, answer: 'They match', options: choices('They match', ['The second phrase reverses', 'Only one phrase plays', 'Both phrases are rests', 'The tempo changes'], random), skill: 'comparing musical phrases', explanation: 'Both phrases use the same pitches in the same order, so they match.' }),
  () => ({ title: 'Different Ending', prompt: 'What changes in the second phrase?', visual: 'compare', musicClue: 'C-E-G | C-E-C', sampleNotes: [262, 330, 392, 0, 262, 330, 262], sampleGapMs: 320, answer: 'The final pitch', options: choices('The final pitch', ['Every pitch', 'Only the first pitch', 'The number of phrases', 'Nothing changes'], random), skill: 'hearing phrase differences', explanation: 'Both phrases begin C-E, but the final pitch changes from G to C.' }),
  () => ({ title: 'Steady Ostinato', prompt: 'Which short pattern keeps repeating?', visual: 'rhythm', musicClue: 'Low, high | low, high | low, high', sampleNotes: [220, 440, 220, 440, 220, 440], sampleGapMs: 300, answer: 'Low, high', options: choices('Low, high', ['High, high', 'Low, low, high', 'Rest, high', 'Three low notes'], random), skill: 'recognizing an ostinato', explanation: 'Low, high repeats without changing, making it an ostinato pattern.' }),
  () => ({ title: 'Finished Melody', prompt: 'Which ending makes the short melody sound complete?', visual: 'melody', musicClue: 'C, E, G, C', sampleNotes: [262, 330, 392, 262], sampleGapMs: 390, answer: 'Return to the starting pitch', options: choices('Return to the starting pitch', ['Stop before any note', 'Add only rests', 'Change every beat randomly', 'Repeat the highest pitch forever'], random), skill: 'hearing musical closure', explanation: 'Returning to the starting pitch gives the phrase a settled, finished sound.' }),
];

const secondGradeFactories = (random: () => number): Array<() => QuestionSeed> => [
  () => ({ title: 'Pitch Leap', prompt: 'How does the first interval move?', visual: 'pitch', musicClue: 'Low C to high G', sampleNotes: [262, 392], sampleGapMs: 520, answer: 'Up by a leap', options: choices('Up by a leap', ['Up by one small step', 'Down by a leap', 'The pitch stays the same', 'A rest only'], random), skill: 'steps and leaps', explanation: 'The pitches are far apart, so the melody moves upward by a leap rather than a small step.' }),
  () => ({ title: 'Three-Beat Group', prompt: 'How many beats repeat in each group?', visual: 'beats', musicClue: 'ONE two three | ONE two three', sampleNotes: [392, 294, 294, 392, 294, 294], sampleGapMs: 360, answer: '3', options: choices('3', ['2', '4', '5', '6'], random), skill: 'hearing meter in threes', explanation: 'A stronger beat returns every three sounds, so the music is grouped in threes.' }),
  () => ({ title: 'Four-Beat Group', prompt: 'How many beats repeat in each group?', visual: 'beats', musicClue: 'ONE two three four | ONE two three four', sampleNotes: [392, 294, 294, 294, 392, 294, 294, 294], sampleGapMs: 330, answer: '4', options: choices('4', ['2', '3', '5', '8'], random), skill: 'hearing meter in fours', explanation: 'A stronger beat returns every four sounds, so the pattern is grouped in fours.' }),
  () => ({ title: 'Eighth-Note Pair', prompt: 'Which rhythm description matches the quick pair?', visual: 'rhythm', musicClue: 'One beat contains two quick sounds', sampleNotes: [330, 392, 0, 330], sampleGapMs: 230, answer: 'Two quick sounds share one beat', options: choices('Two quick sounds share one beat', ['One long rest fills every beat', 'The tempo stops', 'Only one pitch exists', 'Four beats are silent'], random), skill: 'paired eighth-note rhythm', explanation: 'The two close sounds fit inside one beat like a paired eighth-note rhythm.' }),
  () => ({ title: 'Rhythm Equation', prompt: 'Which pattern fills four beats?', visual: 'rhythm', musicClue: 'ta | ti-ti | rest | ta', sampleNotes: [330, 392, 440, 0, 330], sampleGapMs: 300, answer: '1 beat + 1 beat + 1 rest + 1 beat', options: choices('1 beat + 1 beat + 1 rest + 1 beat', ['2 beats total', '5 full beats', 'No rests', 'Only one sound'], random), skill: 'completing four-beat measures', explanation: 'The quarter note, paired quick sounds, rest, and final note each fill one beat for four beats total.' }),
  () => ({ title: 'Question and Answer', prompt: 'How do the two musical phrases relate?', visual: 'compare', musicClue: 'Rising phrase | falling response', sampleNotes: [262, 330, 392, 0, 392, 330, 262], sampleGapMs: 350, answer: 'The second phrase answers the first', options: choices('The second phrase answers the first', ['Both phrases are identical rests', 'There is only one phrase', 'The second phrase has no pitches', 'The tempo doubles forever'], random), skill: 'musical question and answer', explanation: 'The first phrase rises like a question, and the second falls back like an answering phrase.' }),
  () => ({ title: 'Repeated Form', prompt: 'Which form describes the phrases?', visual: 'compare', musicClue: 'A phrase | B phrase | A phrase', sampleNotes: [262, 330, 0, 392, 349, 0, 262, 330], sampleGapMs: 330, answer: 'ABA', options: choices('ABA', ['AAA', 'ABB', 'ABC', 'BAA'], random), skill: 'recognizing ABA form', explanation: 'The first phrase returns after a different middle phrase, creating ABA form.' }),
  () => ({ title: 'AB Form', prompt: 'Which form describes two different phrases?', visual: 'compare', musicClue: 'C-E-G | G-E-C', sampleNotes: [262, 330, 392, 0, 392, 330, 262], sampleGapMs: 330, answer: 'AB', options: choices('AB', ['AA', 'ABA', 'AAA', 'A rest'], random), skill: 'recognizing AB form', explanation: 'The music has one phrase followed by a different phrase, which is AB form.' }),
  () => ({ title: 'Syncopated Surprise', prompt: 'What makes this rhythm feel surprising?', visual: 'rhythm', musicClue: 'Rest, sound, sound, rest, sound', sampleNotes: [0, 392, 330, 0, 392], sampleGapMs: 300, answer: 'Sounds enter after rests', options: choices('Sounds enter after rests', ['Every beat is silent', 'Only one note repeats evenly', 'The pitch never changes', 'The sample has no rhythm'], random), skill: 'off-beat rhythm awareness', explanation: 'The rests delay some sounds, creating an off-beat or syncopated feeling.' }),
  () => ({ title: 'Melody Sequence', prompt: 'What happens to the second three-note pattern?', visual: 'melody', musicClue: 'C-D-E | D-E-F', sampleNotes: [262, 294, 330, 0, 294, 330, 349], sampleGapMs: 320, answer: 'It repeats one step higher', options: choices('It repeats one step higher', ['It repeats one step lower', 'It becomes all rests', 'It reverses every note', 'It changes to one pitch'], random), skill: 'melodic sequences', explanation: 'The same rising three-note shape starts on D instead of C, one step higher.' }),
  () => ({ title: 'Rhythmic Ostinato', prompt: 'Which rhythm is the repeating ostinato?', visual: 'echo', musicClue: 'clap, clap, rest | clap, clap, rest', sampleNotes: [330, 330, 0, 330, 330, 0], sampleGapMs: 330, answer: 'Clap, clap, rest', options: choices('Clap, clap, rest', ['Clap, rest, clap', 'Three rests', 'One clap only', 'Rest, clap, rest'], random), skill: 'rhythmic ostinato', explanation: 'Clap, clap, rest repeats exactly, so it is the rhythmic ostinato.' }),
  () => ({ title: 'Compose an Ending', prompt: 'Which last note best resolves this C-E-G pattern?', visual: 'melody', musicClue: 'C, E, G, ?', sampleNotes: [262, 330, 392], sampleGapMs: 400, answer: 'C', options: choices('C', ['F-sharp', 'A rest before starting', 'No ending', 'A random noise'], random), skill: 'creating melodic closure', explanation: 'Returning to C, the home pitch, gives the phrase a stable ending.' }),
];

export const generateElementaryMusicQuestion = (level: ElementaryMusicLevel, step: number): EarlyMusicQuestion => {
  const random = createSeededRandom(getDailySeed(`elementary-music-grade-${level}`, step));
  const factories = level === 3 ? firstGradeFactories(random) : secondGradeFactories(random);
  const question = factories[Math.floor(random() * factories.length)]();
  return { ...question, id: `elementary-music-${level}-${step}-${question.skill.replace(/[^a-z0-9]+/gi, '-').toLowerCase()}`, phase: PHASES[step % PHASES.length] };
};
