import { createSeededRandom, getDailySeed } from '../dailyRotation';
import { EarlyLiteracyQuestion } from './earlyLiteracy';

export type UpperElementaryLiteracyLevel = 5 | 6 | 7;
const PHASES = ['Warm-up', 'Teacher model', 'Try together', 'Try with less help', 'Spiral review', 'Exit ticket'];
const shuffle = <T,>(items: T[], random: () => number): T[] => {
  const copy = [...items];
  for (let index = copy.length - 1; index > 0; index -= 1) {
    const swapIndex = Math.floor(random() * (index + 1));
    [copy[index], copy[swapIndex]] = [copy[swapIndex], copy[index]];
  }
  return copy;
};
const choices = (answer: string, distractors: string[], random: () => number) => shuffle([answer, ...distractors.filter(item => item !== answer).slice(0, 3)], random);
type Seed = Omit<EarlyLiteracyQuestion, 'id'>;
const q = (prompt: string, focusText: string, answer: string, distractors: string[], skill: string, explanation: string, random: () => number): Seed => ({ prompt, focusText, visual: 'word', answer, options: choices(answer, distractors, random), skill, explanation });

const gradeThree = (random: () => number): Seed[] => [
  q('Divide the word unforgettable into meaningful parts.', 'unforgettable = un + forget + able', 'prefix + base word + suffix', ['base word + base word', 'suffix + prefix only', 'three unrelated words'], 'morphology with prefixes and suffixes', 'Un- is a prefix, forget is the base word, and -able is a suffix that means able to be.', random),
  q('Which syllable division helps decode the word fantastic?', 'fantastic can be read as fan / tas / tic', 'fan / tas / tic', ['fant / astic', 'fa / ntastic', 'fantas / t / ic'], 'decoding multisyllabic words', 'Breaking fantastic into three spoken syllables makes the longer word easier to read accurately.', random),
  q('Read: The desert trail was arid, and not a single puddle remained. What does arid mean?', 'The trail was arid; no puddles remained.', 'very dry', ['very crowded', 'covered with snow', 'full of shade'], 'context clues for vocabulary', 'The clue that no puddles remained shows that arid means extremely dry.', random),
  q('Read: After carrying boxes all morning, Dad said, "These arms are noodles." What did he mean?', 'These arms are noodles.', 'His arms felt weak and tired', ['His arms became food', 'He wanted to cook dinner', 'His sleeves were yellow'], 'literal and nonliteral language', 'The phrase is nonliteral. Comparing his arms to noodles shows they felt weak and tired.', random),
  q('Read: Wetlands hold extra rainwater, provide homes for wildlife, and filter some pollution. What is the main idea?', 'Wetlands store water, shelter wildlife, and filter pollution.', 'Wetlands perform several important jobs', ['Wetlands are always dry', 'Only birds use wetlands', 'Pollution creates wetlands'], 'main idea and supporting details', 'All three details explain a different useful job performed by wetlands.', random),
  q('Read: Mara checked the soil, moved the plant toward the window, and watered it. Two days later, new leaves stood upright. What can you infer?', 'Mara changes the plant care; new leaves stand upright.', 'The plant needed better growing conditions', ['The plant was made of plastic', 'Mara wanted fewer leaves', 'The window blocked all light'], 'inference from multiple clues', 'Mara changed light and water, and the plant improved, suggesting it needed better growing conditions.', random),
  q('Which detail best proves the bridge design improved?', 'First test: 4 blocks. Revised test: 10 blocks.', 'The revised bridge held 10 blocks', ['The paper was blue', 'The team worked at a table', 'Four students watched'], 'selecting relevant text evidence', 'The larger number of blocks directly measures that the revised bridge became stronger.', random),
  q('Read: Eli returned the lost wallet even though no one saw him find it. Which trait best describes Eli?', 'Eli returns a wallet when no one is watching.', 'honest', ['careless', 'impatient', 'confused'], 'character traits from actions', 'Returning something valuable without needing praise shows that Eli is honest.', random),
  q('Read: I gripped the kayak paddle as the current pulled us forward. Who is telling the story?', 'I gripped the kayak paddle.', 'a character using first person', ['an outside narrator', 'the reader', 'a newspaper reporter'], 'identifying narrative point of view', 'The pronoun I shows that a character inside the story is narrating in first person.', random),
  q('Which text structure is used? First rinse the jar. Next add soil. Finally place the seed inside.', 'First ... Next ... Finally ...', 'sequence', ['compare and contrast', 'cause and effect', 'description only'], 'recognizing sequence text structure', 'The signal words first, next, and finally organize the steps in time order.', random),
  q('Text A says city gardens provide food. Text B says they also create habitat for insects. What idea do both texts support?', 'A: gardens provide food. B: gardens help insects.', 'City gardens benefit living things', ['Cities should remove gardens', 'Only insects need food', 'Gardens cannot grow in cities'], 'integrating ideas across two texts', 'Food for people and habitat for insects are both benefits that city gardens provide.', random),
  q('How should this sentence be read? "Wait," called Nia, "the trail turns here!"', '"Wait," called Nia, "the trail turns here!"', 'Pause at commas and emphasize the exclamation', ['Read every word with no pauses', 'Whisper only the last word', 'Stop before the quotation'], 'oral reading fluency and punctuation', 'The commas mark short pauses, while the exclamation point signals stronger expression.', random),
];

const gradeFour = (random: () => number): Seed[] => [
  q('The root port means carry. What does transport most nearly mean?', 'trans = across; port = carry', 'carry from one place to another', ['write about a place', 'look beneath something', 'measure a distance'], 'Greek and Latin roots', 'The prefix trans- means across and port means carry, so transport means carry across or between places.', random),
  q('How does the suffix change predict into predictable?', 'predictable is built from predict + able', 'It means able to be predicted', ['It means before a prediction', 'It means not predicted', 'It changes the word into a place'], 'derivational morphology', 'The suffix -able means capable of, so predictable means capable of being predicted.', random),
  q('Read: The moon was a silver lantern above the campsite. What does the metaphor emphasize?', 'The moon was a silver lantern.', 'The moon looked bright and guiding', ['The moon was made of metal', 'Someone hung a lamp in space', 'The campsite was indoors'], 'interpreting figurative language', 'Comparing the moon to a lantern emphasizes its bright light over the dark campsite.', random),
  q('Read: The scientist was meticulous, checking every measurement twice. What does meticulous mean?', 'She checked every measurement twice.', 'very careful and precise', ['quick and careless', 'loud and excited', 'unable to measure'], 'academic vocabulary in context', 'Checking every measurement twice is evidence that meticulous means very careful and precise.', random),
  q('A character fails twice, studies each mistake, and finally succeeds. Which theme fits best?', 'Failure, reflection, revision, success', 'Mistakes can guide improvement', ['Winning should be immediate', 'Practice is never useful', 'Problems disappear by themselves'], 'determining theme from events', 'The repeated cycle of mistakes, reflection, and success develops the theme that errors can guide improvement.', random),
  q('Which summary is most objective?', 'A storm damages the garden. Neighbors repair beds and build drains.', 'After a storm, neighbors repair the garden and improve its drainage', ['The amazing neighbors save the best garden ever', 'Gardens are obviously better than parks', 'The storm was scary, scary, scary'], 'objective summarizing', 'The best summary includes the central events without opinions, repetition, or unnecessary detail.', random),
  q('Read: Priya packed extra batteries, checked the map twice, and told the group when sunset would occur. What can you infer?', 'Batteries, map checks, sunset planning', 'Priya planned carefully for the trip', ['Priya wanted to get lost', 'The group traveled at noon only', 'The batteries were empty'], 'drawing inferences from details', 'Each action anticipates a possible need, showing that Priya planned carefully.', random),
  q('Which sentence best supports the claim that beavers change habitats?', 'Beavers build dams that slow streams and form ponds.', 'Beavers build dams that form ponds', ['Beavers have thick fur', 'Some beavers are brown', 'Beavers have strong teeth'], 'citing evidence for a claim', 'Creating a dam and pond directly changes the surrounding stream habitat.', random),
  q('Which structure is used? Heavy rain loosened the soil; therefore, the hillside began to slide.', 'Heavy rain loosened soil; therefore, the hill slid.', 'cause and effect', ['chronological sequence', 'compare and contrast', 'question and answer'], 'analyzing cause and effect structure', 'The rain is presented as the cause and the landslide as its resulting effect.', random),
  q('A diary describes a rescue using "I." A history article reports the same event using records. How do the accounts differ?', 'Diary versus history article', 'The diary is firsthand; the article is secondhand', ['Both are fictional', 'Both are written by the rescuer', 'The article has no sources'], 'comparing firsthand and secondhand accounts', 'The diary comes from a participant, while the article reconstructs the event from other sources.', random),
  q('Two sources disagree about when a building opened. What should a reader do?', 'Source A: 1910. Source B: 1912.', 'Check a reliable primary record', ['Choose the larger year', 'Ignore both sources', 'Average the two dates'], 'corroborating information across sources', 'A reliable primary record can resolve the disagreement with direct historical evidence.', random),
  q('An author argues for shade trees and gives temperature measurements from sunny and shaded areas. Why include the data?', 'Sunny: 92 F. Shade: 81 F.', 'To provide evidence that shade lowers temperature', ['To tell a fantasy story', 'To describe tree colors only', 'To prove every day is identical'], 'analyzing claim and evidence', 'The measurements provide relevant numerical evidence supporting the author’s claim about shade.', random),
];

const gradeFive = (random: () => number): Seed[] => [
  q('The root spect means look. What does inspect mean?', 'in + spect = look into', 'look at closely', ['carry across', 'write again', 'speak against'], 'using Greek and Latin roots', 'The root spect means look, and inspect means to look at something closely.', random),
  q('What does reconsideration mean?', 're + consider + ation', 'the act of thinking about something again', ['refusing to think', 'a person who considers', 'thinking before an event'], 'analyzing complex morphology', 'Re- means again, consider means think about, and -ation names the act or process.', random),
  q('Read: Questions erupted around the room like popcorn. What does the simile suggest?', 'Questions erupted like popcorn.', 'Many questions appeared quickly', ['The class cooked a snack', 'Every question sounded the same', 'The room became silent'], 'analyzing figurative language', 'Popcorn pops rapidly in many places, suggesting that many questions appeared quickly.', random),
  q('Which word best completes the sentence? The evidence did not prove the claim, but it did ___ that the claim might be true.', 'Evidence did not prove, but it did ...', 'suggest', ['announce', 'guarantee', 'command'], 'word relationships and nuance', 'Suggest shows partial support without claiming the evidence proves or guarantees the conclusion.', random),
  q('A student hides a mistake, sees the harm it causes, admits it, and repairs the project. Which theme is developed?', 'Mistake, concealment, admission, repair', 'Taking responsibility helps rebuild trust', ['Secrets always solve problems', 'Projects should never change', 'Trust does not depend on actions'], 'analyzing theme development', 'The character restores the project and relationships only after accepting responsibility.', random),
  q('Which summary best captures the passage?', 'Researchers tag butterflies, track migration, compare routes, and protect resting places.', 'Scientists study butterfly routes to understand and protect migration', ['Butterflies have colorful wings', 'Tagging is the only kind of science', 'Every butterfly follows one identical route'], 'summarizing informational text', 'The summary combines the research process and its conservation purpose without minor details.', random),
  q('Read: The team brought extra rope, tested knots indoors, and checked the wind report. What conclusion is best supported?', 'Extra rope, knot tests, wind report', 'The team reduced risks before working outside', ['The team disliked planning', 'The work required no equipment', 'Wind cannot affect outdoor work'], 'inference and logical conclusion', 'The preparations address equipment and weather risks before the outdoor task begins.', random),
  q('Which quotation is strongest evidence that the narrator’s opinion changed?', 'At first I called the plan impossible. After the test, I asked to help build it.', 'After the test, I asked to help build it', ['The room had four windows', 'The plan used cardboard', 'We met on Tuesday'], 'quoting evidence accurately', 'Asking to help after calling the plan impossible directly demonstrates a changed opinion.', random),
  q('A passage introduces polluted water, explains failed filters, then presents a successful redesign. Which structure dominates?', 'Problem, failed attempts, successful redesign', 'problem and solution', ['compare and contrast only', 'spatial description', 'unrelated questions'], 'analyzing text structure', 'The passage centers on a problem and organizes attempts leading to a successful solution.', random),
  q('How does first-person narration affect a storm-rescue story?', 'I could not see the trail, but I heard Maya call my name.', 'It reveals the narrator’s direct thoughts and limited view', ['It explains every character’s thoughts', 'It removes all emotion', 'It guarantees the account is unbiased'], 'analyzing point of view', 'First person gives direct access to one narrator’s experience but limits information to what that narrator knows.', random),
  q('Text A explains that green roofs reduce heat. Text B reports a school roof attracting insects. What conclusion uses both texts?', 'A: cooler buildings. B: insect habitat.', 'Green roofs can benefit buildings and local ecosystems', ['Green roofs have only one purpose', 'Insects always increase heat', 'Schools should remove all roofs'], 'synthesizing paired texts', 'Combining both texts shows benefits for building temperature and the surrounding ecosystem.', random),
  q('Which evidence most strongly supports a claim that later school start times improve alertness?', 'Students slept 35 minutes longer and morning attention scores increased.', 'Sleep duration and attention scores both increased', ['The buses were painted blue', 'The school mascot changed', 'Lunch used the same menu'], 'evaluating argument evidence', 'The sleep and attention data are directly relevant and measurable evidence for improved alertness.', random),
];

export const generateUpperElementaryLiteracyQuestion = (level: UpperElementaryLiteracyLevel, step: number): EarlyLiteracyQuestion => {
  const random = createSeededRandom(getDailySeed(`upper-elementary-reading-grade-${level}`, step));
  const bank = level === 5 ? gradeThree(random) : level === 6 ? gradeFour(random) : gradeFive(random);
  const question = bank[step % bank.length];
  return { ...question, id: `upper-reading-${level}-${step}-${question.skill.replace(/[^a-z0-9]+/gi, '-').toLowerCase()}`, prompt: `${PHASES[step % PHASES.length]}: ${question.prompt}` };
};
