import { createSeededRandom, getDailySeed } from '../dailyRotation';
import { EarlyWorldQuestion, EarlyWorldVisual } from './earlyWorld';

export type UpperElementaryWorldLevel = 5 | 6 | 7;
const PHASES = ['Read the map', 'Study the source', 'Connect cause and effect', 'Compare perspectives', 'Use evidence', 'World Studies check'];
const shuffle = <T,>(items: T[], random: () => number): T[] => { const copy = [...items]; for (let i = copy.length - 1; i > 0; i -= 1) { const j = Math.floor(random() * (i + 1)); [copy[i], copy[j]] = [copy[j], copy[i]]; } return copy; };
const q = (title: string, prompt: string, mapClue: string, answer: string, distractors: string[], skill: string, explanation: string, random: () => number, visual: EarlyWorldVisual = 'map-symbol'): Omit<EarlyWorldQuestion, 'id' | 'phase'> => ({ title, prompt, mapClue, answer, options: shuffle([answer, ...distractors.slice(0, 3)], random), skill, explanation, visual });

const gradeThree = (r: () => number) => [
  q('Map Scale', 'A map scale says 1 inch equals 5 miles. Two towns are 3 inches apart. What is the real distance?', '1 inch = 5 miles | map distance = 3 inches', '15 miles', ['8 miles', '5 miles', '30 miles'], 'using map scale', 'Multiply the three map inches by five miles per inch to find 15 real miles.', r),
  q('Regional Features', 'Which feature best defines a coastal region?', 'Region borders an ocean and includes beaches and ports.', 'land next to an ocean', ['land surrounded by mountains only', 'a place with no water', 'one city block'], 'identifying geographic regions', 'A coastal region is defined by its location beside an ocean or sea.', r, 'land-water'),
  q('People and Environment', 'Why might a town build homes on raised foundations?', 'The river rises above its banks during some seasons.', 'to reduce flood damage', ['to create earthquakes', 'to stop all rainfall', 'to remove the river'], 'human adaptation to environment', 'Raised foundations are an adaptation that keeps living spaces above expected floodwater.', r, 'weather'),
  q('Trade Route', 'Why did communities often grow near navigable rivers?', 'Rivers connect farms, towns, and ports.', 'Rivers helped move people and goods', ['Rivers ended all trade', 'Boats could travel on roads only', 'Water made farming impossible'], 'transportation and trade geography', 'Navigable rivers provided efficient routes for transportation, exchange, and settlement.', r, 'resources'),
  q('Scarcity Choice', 'A town has money for either a new playground or a library roof repair. What is the opportunity cost of choosing the roof?', 'Budget allows only one project this year.', 'the playground that is delayed', ['the repaired roof', 'all future taxes', 'the town map'], 'scarcity and opportunity cost', 'Opportunity cost is the next-best choice given up, which is the delayed playground.', r, 'community'),
  q('Local Government', 'Which local service is most likely managed by city government?', 'Residents need streets repaired and trash collected.', 'street repair and waste collection', ['printing national money', 'negotiating with other countries', 'commanding the national military'], 'local government services', 'Municipal governments commonly manage local infrastructure and sanitation services.', r, 'community'),
  q('Civic Responsibility', 'Which action shows responsible community participation?', 'Residents disagree about a park design.', 'Attend the meeting, listen, and share evidence', ['Damage the park', 'Spread false information', 'Prevent others from speaking'], 'civic participation and responsibility', 'Responsible participation combines informed input, respectful listening, and lawful action.', r, 'community'),
  q('Timeline Reasoning', 'Which event belongs second?', '1900 school opens | 1915 library opens | 1930 bridge opens', 'The library opens in 1915', ['The bridge opens in 1930', 'The school opens in 1900', 'All happen together'], 'chronological order on timelines', '1915 falls after 1900 and before 1930, so the library event is second.', r, 'traditions'),
  q('Primary Source', 'Which item is a primary source for studying a 1920 school day?', 'Choose evidence created during the time being studied.', 'a student diary written in 1920', ['a modern textbook summary', 'a recent documentary', 'a website article written today'], 'distinguishing primary and secondary sources', 'A diary written by a participant during 1920 is direct evidence from the historical period.', r, 'traditions'),
  q('Historical Cause', 'A railroad reaches a small town, and new stores open nearby. What is the strongest cause-and-effect claim?', 'Rail service begins -> travel and shipping increase -> stores open', 'The railroad helped the town’s economy grow', ['Stores caused the railroad to vanish', 'Travel became impossible', 'The events are unrelated'], 'historical cause and effect', 'Improved transportation can increase customers and shipping, supporting local business growth.', r, 'community'),
  q('Cultural Exchange', 'What can happen when families from different places share food, music, and stories?', 'Community festival includes many traditions.', 'The community learns and combines cultural traditions', ['Every tradition becomes identical', 'People forget all history', 'Maps stop showing places'], 'cultural exchange and traditions', 'Sharing practices allows people to learn from one another while maintaining meaningful traditions.', r, 'traditions'),
  q('Map Evidence', 'Which conclusion is best supported by the population map?', 'Most large towns cluster along the river and highway.', 'Transportation routes influenced settlement locations', ['People avoid all roads', 'Every town has equal population', 'The river prevents settlement'], 'drawing conclusions from geographic data', 'The clustering pattern supports a relationship between transportation access and settlement.', r, 'directions'),
];

const gradeFour = (r: () => number) => [
  q('Physical Regions', 'Which evidence best identifies a mountainous region?', 'Map shows steep elevation lines, narrow valleys, and high peaks.', 'high elevation and steep slopes', ['flat low land', 'ocean water only', 'no variation in elevation'], 'physical geography and regions', 'Closely spaced elevation lines and high peaks indicate steep mountainous terrain.', r, 'land-water'),
  q('Indigenous Adaptation', 'Why did Indigenous nations develop different housing and food systems across North America?', 'Regions offered different climates, plants, animals, and materials.', 'Communities adapted to local environments and resources', ['All regions had identical resources', 'Geography never affects life', 'One design was required everywhere'], 'Indigenous cultures and environment', 'Distinct environments shaped locally effective technologies, foodways, and shelter while cultures remained dynamic.', r, 'traditions'),
  q('Settlement Location', 'Why would settlers choose a site near fresh water and fertile soil?', 'Site includes river access, farmable land, and a natural harbor.', 'It supports farming, drinking water, and transportation', ['It prevents all trade', 'It guarantees no conflict', 'It removes every hazard'], 'geographic factors in settlement', 'Water, productive soil, and transportation access support community survival and trade.', r, 'resources'),
  q('Colonial Economy', 'Which region is most suited to a shipping economy?', 'Deep harbor, navigable coast, limited inland farmland', 'a coastal port region', ['an isolated desert', 'a landlocked mountain peak', 'a frozen lake with no route'], 'regional specialization and trade', 'A deep harbor and navigable coast make shipping and maritime trade practical.', r, 'land-water'),
  q('Migration Push-Pull', 'Which is a pull factor?', 'Family considers moving because another town offers jobs and safer housing.', 'available jobs and safer housing', ['crop failure at home', 'a damaging storm', 'loss of local work'], 'migration push and pull factors', 'Pull factors attract people to a destination, such as opportunity and safety.', r, 'community'),
  q('State Government', 'Which responsibility usually belongs to state government?', 'Issue driver licenses and operate statewide public systems.', 'issuing driver licenses', ['printing U.S. currency', 'negotiating treaties', 'running one family business'], 'state and federal responsibilities', 'Driver licensing is generally administered by state governments under state law.', r, 'community'),
  q('Rule of Law', 'What does rule of law mean?', 'Leaders and residents are governed by publicly known laws.', 'Laws apply to everyone, including leaders', ['Leaders are above every law', 'Rules stay secret', 'Only visitors follow laws'], 'rule of law and civic principles', 'Rule of law limits power by requiring both officials and citizens to follow established laws.', r, 'community'),
  q('Economic Specialization', 'Why might one region produce apples while another produces cotton?', 'Climate and soil conditions differ by region.', 'Regions specialize based on resources and conditions', ['All crops grow equally everywhere', 'Trade removes climate', 'Soil has no effect on farming'], 'specialization and interdependence', 'Different environmental advantages encourage specialization and trade between regions.', r, 'resources'),
  q('Historical Evidence', 'Which source best confirms how many people lived in a town in 1880?', 'Choose the record created to count residents.', 'the 1880 census record', ['a modern novel', 'an undated painting', 'a present-day travel ad'], 'using historical records as evidence', 'A census was created to record population information for that time and place.', r, 'traditions'),
  q('Multiple Perspectives', 'Why might two people describe the same land policy differently?', 'One gains land; another community is displaced.', 'Their experiences and interests differ', ['Only one person can remember', 'Evidence has no value', 'Perspective changes the date'], 'comparing historical perspectives', 'People can interpret an event differently because its effects on their lives differ.', r, 'traditions'),
  q('Chronology and Change', 'Which statement shows change over time?', '1800: wagon route | 1850: railroad | 1950: highway', 'Transportation became faster and connected more places', ['Every route stayed identical', 'The highway existed first', 'Travel ended in 1850'], 'analyzing change over time', 'The sequence shows newer transportation systems increasing speed and connections.', r, 'directions'),
  q('Civic Decision', 'Which process best supports a fair public decision?', 'A town must choose one of three park plans.', 'Publish options, hear community views, and vote lawfully', ['Hide the options', 'Let one person decide secretly', 'Exclude affected residents'], 'democratic decision-making', 'Transparent information, participation, and lawful voting support accountable public choices.', r, 'community'),
];

const gradeFive = (r: () => number) => [
  q('Latitude and Longitude', 'Which coordinate comes first in a geographic coordinate pair?', 'Location written as 47 N, 122 W', 'latitude', ['longitude', 'elevation', 'map scale'], 'using latitude and longitude', 'Latitude is conventionally listed before longitude when identifying global coordinates.', r, 'directions'),
  q('Climate and Settlement', 'Why do major cities often develop near coasts and rivers?', 'Map shows ports, fresh water, and transportation routes.', 'Waterways support trade, resources, and movement', ['Waterways prevent exchange', 'Cities require deserts', 'Rivers remove all hazards'], 'geography and settlement patterns', 'Water access can support transportation, commerce, food systems, and daily needs.', r, 'land-water'),
  q('Columbian Exchange', 'Which statement accurately describes the Columbian Exchange?', 'Plants, animals, people, diseases, and ideas moved across the Atlantic.', 'It connected continents with major benefits and harms', ['It affected only one crop', 'It involved no people', 'It ended all trade'], 'Columbian Exchange consequences', 'Atlantic exchange transformed societies while also causing disease, exploitation, and displacement.', r, 'resources'),
  q('Revolutionary Causes', 'Which issue contributed to colonial protest against Britain?', 'Colonists faced taxes while lacking elected representation in Parliament.', 'taxation without representation', ['too many local elections', 'free land for everyone', 'the end of Atlantic trade'], 'causes of the American Revolution', 'Many colonists argued that taxation without political representation violated their rights.', r, 'traditions'),
  q('Constitutional Structure', 'Why does the U.S. Constitution divide federal power among branches?', 'Legislative, executive, and judicial powers are separated.', 'to prevent one branch from controlling all power', ['to eliminate laws', 'to end courts', 'to make elections unnecessary'], 'separation of powers', 'Dividing authority creates checks and reduces the risk of concentrated government power.', r, 'community'),
  q('Rights and Responsibilities', 'Which statement correctly connects a right and responsibility?', 'People may express views and should respect others’ lawful expression.', 'Rights are protected alongside civic responsibilities', ['Rights remove every rule', 'Only officials have rights', 'Responsibilities cancel freedoms'], 'constitutional rights and civic responsibilities', 'A democratic society protects individual freedoms while relying on responsible participation.', r, 'community'),
  q('Westward Expansion', 'Why should historians examine multiple perspectives on westward expansion?', 'Settlers gained opportunities while Indigenous nations faced dispossession.', 'The same expansion affected groups in very different ways', ['Only maps matter', 'Every group had the same experience', 'Consequences ended immediately'], 'multiple perspectives in westward expansion', 'Comparing perspectives reveals gains, conflicts, forced removal, and lasting consequences.', r, 'traditions'),
  q('Industrial Change', 'How did factories and railroads change the economy?', 'Production increased and goods moved farther and faster.', 'They expanded production, markets, and urban growth', ['They ended migration', 'They stopped invention', 'They eliminated working conditions'], 'industrialization and economic change', 'Mechanized production and transportation connected larger markets and accelerated city growth.', r, 'resources'),
  q('Supply and Demand', 'A popular item is scarce while many buyers want it. What may happen to its price?', 'Supply decreases while demand remains high.', 'The price may rise', ['The price must become zero', 'Demand disappears automatically', 'Scarcity creates more supply instantly'], 'supply demand and price', 'When demand exceeds available supply, competition among buyers can push price upward.', r, 'resources'),
  q('Source Perspective', 'A campaign speech praises only one candidate. What should a historian consider?', 'The source was created to persuade voters.', 'The author’s purpose may shape the message', ['The speech contains every perspective', 'Persuasion guarantees neutrality', 'Purpose never matters'], 'source purpose and bias', 'A persuasive purpose can influence which facts and viewpoints the speaker emphasizes or omits.', r, 'traditions'),
  q('Civic Participation', 'Which action can lawfully influence public policy?', 'Residents want safer crossings near school.', 'Present evidence at a council meeting and contact representatives', ['Damage traffic signs', 'Threaten other residents', 'Spread invented statistics'], 'informed civic action', 'Evidence-based communication with public officials is a lawful way to advocate for change.', r, 'community'),
  q('Corroborating Sources', 'Two accounts disagree about an event. What is the strongest next step?', 'Account A and B give different causes.', 'Compare additional reliable primary and secondary sources', ['Choose the shorter account', 'Ignore all evidence', 'Combine claims without checking'], 'corroboration and historical interpretation', 'Corroborating several reliable sources helps evaluate claims, context, and perspective.', r, 'traditions'),
];

export const generateUpperElementaryWorldQuestion = (level: UpperElementaryWorldLevel, step: number): EarlyWorldQuestion => {
  const random = createSeededRandom(getDailySeed(`upper-elementary-world-grade-${level}`, step));
  const bank = level === 5 ? gradeThree(random) : level === 6 ? gradeFour(random) : gradeFive(random);
  const question = bank[step % bank.length];
  return { ...question, id: `upper-world-${level}-${step}-${question.skill.replace(/[^a-z0-9]+/gi, '-').toLowerCase()}`, phase: PHASES[step % PHASES.length] };
};
