import { createSeededRandom, getDailySeed } from '../dailyRotation';
import { EarlyScienceQuestion, EarlyScienceVisual } from './earlyScience';

export type UpperElementaryScienceLevel = 5 | 6 | 7;
const PHASES = ['Observe', 'Predict', 'Compare', 'Test an idea', 'Use evidence', 'Explain'];
const shuffle = <T,>(items: T[], random: () => number): T[] => { const copy = [...items]; for (let i = copy.length - 1; i > 0; i -= 1) { const j = Math.floor(random() * (i + 1)); [copy[i], copy[j]] = [copy[j], copy[i]]; } return copy; };
const q = (title: string, prompt: string, observation: string, answer: string, distractors: string[], skill: string, evidence: string, explanation: string, random: () => number, visual: EarlyScienceVisual = 'pattern'): Omit<EarlyScienceQuestion, 'id' | 'phase'> => ({ title, prompt, observation, answer, options: shuffle([answer, ...distractors.slice(0, 3)], random), skill, evidence, explanation, visual });

const gradeThree = (r: () => number) => [
  q('Balanced Forces', 'Two teams pull equally in opposite directions. What happens to the rope?', 'Left pull: 40 N | Right pull: 40 N', 'It stays in the same position', ['It speeds left', 'It speeds right', 'It disappears'], 'balanced and unbalanced forces', 'The forces have equal strength and opposite directions.', 'Equal opposite forces are balanced, so they do not change the rope’s motion.', r, 'force'),
  q('Magnet Test', 'Which setup will create a pushing force?', 'Two bar magnets can attract or repel.', 'Place two north poles facing each other', ['Place north facing south', 'Remove both magnets', 'Place one magnet beside wood'], 'magnetic forces at a distance', 'Like magnetic poles repel while opposite poles attract.', 'Two north poles repel, producing a push without the magnets touching.', r, 'force'),
  q('Motion Pattern', 'A pendulum takes 2 seconds for every swing. What should happen on the next swing?', 'Swing times: 2 s, 2 s, 2 s', 'It should take about 2 seconds', ['It must take 20 seconds', 'It will stop time', 'It becomes a magnet'], 'predicting motion patterns', 'Three repeated swings took the same amount of time.', 'The repeated timing pattern supports predicting another swing of about 2 seconds.', r),
  q('Inherited Trait', 'Which trait is most likely inherited from parents?', 'Young rabbits vary in fur color and learned behaviors.', 'fur color', ['responding to a whistle', 'finding a trained path', 'opening a latch after practice'], 'inherited traits', 'Fur color is present without the rabbit being taught.', 'Inherited traits are passed from parents, while trained actions are learned.', r, 'animal'),
  q('Environmental Effect', 'Two identical plants get equal water, but one gets less light. Why may their growth differ?', 'Plant A: 8 h light | Plant B: 2 h light', 'Their environments provide different light', ['Their species changed', 'Water stopped being matter', 'The pots changed their genes'], 'environmental effects on traits', 'Light exposure is the only recorded difference.', 'Environmental conditions such as light can affect how strongly a plant grows.', r, 'plant'),
  q('Survival Advantage', 'Which trait would best help an animal reach insects inside tree bark?', 'Food is hidden in narrow holes in bark.', 'a long narrow beak', ['flat swimming feet', 'thick white fur', 'a short round tail'], 'traits and survival', 'A narrow tool can enter the same small spaces where the insects live.', 'A long narrow beak gives the animal better access to food inside bark.', r, 'animal'),
  q('Fossil Evidence', 'What can a shell fossil found in desert rock suggest?', 'Marine shell fossil embedded far from today’s ocean', 'The area was once covered by water', ['The shell flew there yesterday', 'Deserts cannot change', 'The rock is younger than today'], 'fossils and past environments', 'Marine organisms normally live in water.', 'The fossil is evidence that the environment was once aquatic even though it is dry now.', r, 'water'),
  q('Climate Pattern', 'Which statement describes climate rather than one day of weather?', 'Region data collected for 30 years', 'Winters are usually cold and snowy', ['It rained this afternoon', 'Today is 72 degrees', 'A storm begins tonight'], 'weather and climate patterns', 'The statement summarizes conditions repeated over many years.', 'Climate describes long-term patterns, while weather describes short-term conditions.', r, 'weather'),
  q('Hazard Design', 'Which design best reduces flood damage to a model house?', 'Water repeatedly rises 4 cm above the ground.', 'Raise the house on supports higher than 4 cm', ['Put paper under the house', 'Remove every drain', 'Build below ground level'], 'reducing weather hazard impacts', 'The recorded flood height reaches 4 centimeters.', 'Supports above the measured water level keep the house out of the model flood.', r, 'water'),
  q('Fair Ramp Test', 'To test how ramp height affects distance, what should stay the same?', 'Only ramp height should change between trials.', 'the same car and floor surface', ['the ramp height', 'the measured result', 'the prediction'], 'planning controlled investigations', 'Changing only one variable allows a fair comparison.', 'Keeping the car and surface constant isolates ramp height as the tested variable.', r, 'force'),
  q('Data Claim', 'Which claim is supported by the cart data?', '10 cm ramp: 35 cm | 20 cm ramp: 68 cm | 30 cm ramp: 101 cm', 'Higher ramps made the cart travel farther', ['Ramp height had no effect', 'The lowest ramp went farthest', 'All distances were equal'], 'interpreting investigation data', 'Distance increased each time ramp height increased.', 'The consistent increase in distance supports the claim that higher ramps produced farther travel.', r, 'force'),
  q('Engineering Revision', 'A windbreak falls in every high-wind test. What should engineers do next?', 'Failure occurs where the narrow base meets the ground.', 'Widen the base and test again', ['Hide the failed trials', 'Keep every feature unchanged', 'Remove the wind test'], 'engineering design revision', 'The failure location identifies the narrow base as a weak point.', 'Widening the base directly addresses the evidence and should be tested as a revision.', r, 'weather'),
];

const gradeFour = (r: () => number) => [
  q('Energy Transfer', 'Why does a metal spoon warm in hot soup?', 'The spoon touches soup that is warmer than the spoon.', 'Thermal energy moves from soup to spoon', ['Cold moves into the soup', 'The spoon creates sunlight', 'Matter stops moving'], 'thermal energy transfer', 'Energy moves from a warmer object toward a cooler object.', 'Contact allows thermal energy to transfer from the hot soup into the cooler spoon.', r, 'sunlight'),
  q('Electric Circuit', 'Which circuit will light the bulb?', 'Battery, wires, and bulb must form one complete path.', 'a closed loop through the battery and bulb', ['a loop with a wire gap', 'one wire touching nothing', 'a bulb beside a battery'], 'closed electrical circuits', 'Electric current requires an unbroken conducting path.', 'A closed loop lets current travel through the bulb and back to the battery.', r, 'force'),
  q('Energy Conversion', 'What energy change occurs in a battery-powered fan?', 'Battery powers a spinning motor.', 'stored chemical energy becomes motion energy', ['motion becomes sunlight', 'sound becomes matter', 'gravity becomes food'], 'energy conversion', 'The battery stores energy and the motor produces motion.', 'The system transforms stored chemical energy into electrical and then motion energy.', r, 'force'),
  q('Wave Pattern', 'Which change creates a higher-pitched rubber-band sound?', 'Tighter bands vibrate more quickly.', 'Increase the vibration frequency', ['Stop all vibration', 'Make each vibration slower', 'Cover the band with clay'], 'waves and sound pitch', 'Higher pitch is associated with faster vibration frequency.', 'Tightening the band increases vibration frequency, producing a higher pitch.', r),
  q('Light and Vision', 'Why can you see a book in a lit room?', 'Lamp light reaches the book and then your eyes.', 'Light reflects from the book into your eyes', ['Eyes send darkness to the book', 'The book makes all its own light', 'Sound carries the image'], 'reflected light and vision', 'The book is visible only when light travels from it to the observer.', 'Reflected light carries visual information from the book into the eyes.', r, 'sunlight'),
  q('Structure and Function', 'Why do many plant leaves have broad flat surfaces?', 'Broad leaves expose more surface to sunlight.', 'to capture light for making food', ['to hide every root', 'to stop all gas exchange', 'to make the plant magnetic'], 'plant structures and functions', 'The broad surface increases the area receiving sunlight.', 'More exposed leaf area helps the plant capture light used to make sugars.', r, 'plant'),
  q('Sensory Information', 'Which pathway best describes seeing a moving ball?', 'Light enters eyes; nerves carry signals; brain responds.', 'eyes detect light, nerves signal the brain, body reacts', ['brain shines light from the eyes', 'muscles see without nerves', 'the ball controls the brain'], 'sensory processing and response', 'Receptors detect information and nerves carry signals.', 'The nervous system processes visual information before directing a body response.', r, 'senses'),
  q('Weathering', 'Water freezes inside a rock crack and expands. What may happen over many cycles?', 'Freeze-thaw repeats through winter.', 'The crack widens and the rock breaks', ['The rock turns into a plant', 'The crack seals permanently', 'Gravity stops'], 'physical weathering', 'Freezing water expands and pushes against the crack walls.', 'Repeated expansion can widen cracks and break rock into smaller pieces.', r, 'water'),
  q('Earth Systems', 'How can heavy rain affect both land and rivers?', 'Runoff moves loose soil downhill into streams.', 'It can erode soil and carry sediment into rivers', ['It removes all gravity', 'It creates new sunlight', 'It stops the water cycle'], 'interactions among Earth systems', 'Moving water connects land material with stream water.', 'Rain links the atmosphere, land, and water by causing erosion and sediment transport.', r, 'water'),
  q('Resource Choice', 'Which energy source is renewable on a human time scale?', 'Compare sunlight, coal, oil, and natural gas.', 'sunlight', ['coal', 'oil', 'natural gas'], 'renewable and nonrenewable resources', 'Sunlight is continuously supplied, while fossil fuels form extremely slowly.', 'Solar energy is renewable because its source is replenished continuously.', r, 'sunlight'),
  q('Design Constraints', 'A water collector must hold 500 mL, cost under $5, and not leak. Which result meets every constraint?', 'A: 600 mL, $4, no leak | B: 450 mL, $3 | C: 700 mL, $7', 'Design A', ['Design B', 'Design C', 'All designs'], 'engineering criteria and constraints', 'Only Design A meets capacity, cost, and leak requirements.', 'A successful solution must satisfy every stated criterion and constraint at the same time.', r, 'water'),
  q('Repeated Trials', 'Why test the same insulator three times?', 'Trial results: 18 C, 19 C, 18 C', 'to check whether the result is consistent', ['to change the question each time', 'to guarantee the prediction', 'to avoid recording data'], 'reliability through repeated trials', 'Similar repeated measurements increase confidence in the pattern.', 'Repeated trials reveal whether a result is dependable rather than a one-time accident.', r, 'sunlight'),
];

const gradeFive = (r: () => number) => [
  q('Particle Model', 'Why does sugar seem to disappear when stirred into water?', 'The liquid stays clear but tastes sweet.', 'Sugar particles spread through the water', ['Sugar stops being matter', 'Water destroys every particle', 'The particles become light'], 'particle model of matter', 'Sweet taste throughout the liquid shows sugar is still present.', 'Dissolving spreads sugar particles too widely to see while conserving the matter.', r, 'water'),
  q('Conservation of Matter', 'A sealed bag contains 100 g before ice melts. What mass should it have after melting?', 'No material enters or leaves the sealed bag.', '100 g', ['0 g', '50 g', '200 g'], 'conservation of matter', 'Melting changes state but does not add or remove particles.', 'In a closed system, matter is conserved during a physical state change.', r, 'water'),
  q('Separating Mixtures', 'How can iron filings be separated from sand?', 'Iron responds to magnets; sand does not.', 'Use a magnet', ['Add more sand', 'Shine a flashlight', 'Freeze both solids'], 'properties and mixture separation', 'Magnetism is a property that differs between the two materials.', 'A magnet attracts the iron while leaving the nonmagnetic sand behind.', r, 'force'),
  q('Chemical Change', 'Which observation best indicates a new substance formed?', 'Two clear liquids mix, warm up, and form a solid.', 'A solid forms with an unexpected temperature change', ['Ice melts into water', 'Paper is cut smaller', 'Salt dissolves'], 'evidence of chemical reactions', 'A new solid and energy change are evidence of new substances.', 'Multiple unexpected property changes support identifying a chemical reaction.', r, 'senses'),
  q('Plant Matter', 'Where does most of a tree’s dry mass come from?', 'Tree takes in carbon dioxide, water, and light.', 'carbon dioxide from the air', ['soil that vanishes', 'sunlight turning directly into matter', 'rocks absorbed by leaves'], 'photosynthesis and plant matter', 'Plants use carbon from carbon dioxide to build sugars and tissues.', 'Most plant dry mass comes from carbon atoms taken from atmospheric carbon dioxide.', r, 'plant'),
  q('Food Web', 'If insect numbers drop sharply, which organism is most directly affected?', 'grass -> insect -> frog -> hawk', 'frog', ['grass only', 'rock', 'sunlight'], 'food webs and energy flow', 'Frogs directly consume insects in the shown food chain.', 'A drop in the frog’s direct food source can reduce available energy for frogs.', r, 'habitat'),
  q('Matter Cycle', 'What role do decomposers play in an ecosystem?', 'Fungi break down dead leaves into simpler materials.', 'They return matter to soil and the food web', ['They create matter from nothing', 'They stop all plant growth', 'They remove every nutrient'], 'cycling matter in ecosystems', 'Materials from dead organisms become available in the environment again.', 'Decomposers recycle matter, allowing nutrients to be reused by producers.', r, 'habitat'),
  q('Gravity', 'Why does a dropped ball accelerate toward the ground?', 'The ball and Earth attract each other.', 'Earth’s gravity pulls the ball downward', ['Air pushes it toward space', 'The ball loses all mass', 'Sunlight becomes a force'], 'gravity as an attractive force', 'The direction of motion is consistently toward Earth’s center.', 'Gravity is a noncontact attractive force acting between Earth and the ball.', r, 'force'),
  q('Star Brightness', 'Why does the sun appear brighter than other stars?', 'The sun is the closest star to Earth.', 'It is much closer to Earth', ['It is the only star', 'Other stars make no light', 'Earth blocks every other star'], 'apparent brightness of stars', 'Distance strongly affects how bright a light source appears.', 'The sun’s relative closeness makes it appear far brighter than distant stars.', r, 'sky'),
  q('Earth Systems', 'How does vegetation affect the water cycle?', 'Roots absorb water; leaves release water vapor.', 'Plants move water from soil into the atmosphere', ['Plants stop evaporation everywhere', 'Roots create new oceans', 'Leaves remove all clouds'], 'water cycling through Earth systems', 'Water enters roots and later leaves through leaf openings.', 'Transpiration transfers water from the biosphere into the atmosphere.', r, 'water'),
  q('Water Distribution', 'Which statement best describes Earth’s water?', 'Most water is salty ocean water; little freshwater is easily available.', 'Most is saltwater, and accessible freshwater is limited', ['Most is drinkable river water', 'Freshwater is unlimited', 'Oceans contain no water'], 'distribution of Earth water', 'Measurements show oceans hold the overwhelming majority of Earth’s water.', 'Only a small fraction of Earth’s water is accessible freshwater for organisms and people.', r, 'water'),
  q('Evidence-Based Design', 'Which design conclusion is best supported?', 'Filter A: 30 particles | B: 12 | C: 4 particles after filtering', 'Filter C removed the most particles', ['Filter A worked best', 'All filters were equal', 'No data were collected'], 'analyzing engineering performance data', 'The lowest remaining particle count indicates the greatest removal.', 'Filter C left the fewest particles, so the data support it as the strongest performer.', r, 'water'),
];

export const generateUpperElementaryScienceQuestion = (level: UpperElementaryScienceLevel, step: number): EarlyScienceQuestion => {
  const random = createSeededRandom(getDailySeed(`upper-elementary-science-grade-${level}`, step));
  const bank = level === 5 ? gradeThree(random) : level === 6 ? gradeFour(random) : gradeFive(random);
  const question = bank[step % bank.length];
  return { ...question, id: `upper-science-${level}-${step}-${question.skill.replace(/[^a-z0-9]+/gi, '-').toLowerCase()}`, phase: PHASES[step % PHASES.length] };
};
