import { MathProblem } from '../../types';
import { createSeededRandom, getDailySeed } from '../dailyRotation';

export type UpperElementaryMathLevel = 5 | 6 | 7;

const PHASES = ['Warm-up', 'Teacher model', 'Try together', 'Try with less help', 'Spiral review', 'Exit ticket'];
const shuffle = <T,>(items: T[], random: () => number): T[] => {
  const copy = [...items];
  for (let index = copy.length - 1; index > 0; index -= 1) {
    const swapIndex = Math.floor(random() * (index + 1));
    [copy[index], copy[swapIndex]] = [copy[swapIndex], copy[index]];
  }
  return copy;
};
const options = <T extends number | string>(answer: T, distractors: T[], random: () => number): T[] => shuffle([answer, ...[...new Set(distractors)].filter(item => item !== answer).slice(0, 3)], random);
const wholeOptions = (answer: number, random: () => number) => options(answer, [answer - 10, answer - 5, answer - 2, answer - 1, answer + 1, answer + 2, answer + 5, answer + 10].filter(value => value >= 0), random).slice(0, 4);
type Factory = () => MathProblem;

const gradeThree = (random: () => number): Factory[] => [
  () => { const rows = 3 + Math.floor(random() * 5); const columns = 2 + Math.floor(random() * 6); const answer = rows * columns; return { question: `${rows} rows have ${columns} tiles each. How many tiles are in the array?`, answer, options: wholeOptions(answer, random), operation: 'multiplication', context: 'word-problem', difficulty: 5, skill: 'multiplication with arrays', explanation: `${rows} equal rows of ${columns} represent ${rows} x ${columns} = ${answer}.`, visualModel: { kind: 'array', rows, columns } }; },
  () => { const groups = 3 + Math.floor(random() * 6); const each = 2 + Math.floor(random() * 7); const total = groups * each; return { question: `${total} counters are shared into ${groups} equal groups. How many are in each group?`, answer: each, options: wholeOptions(each, random), operation: 'division', context: 'word-problem', difficulty: 5, skill: 'division as equal sharing', explanation: `${total} divided into ${groups} equal groups gives ${each} in each group.`, visualModel: { kind: 'bar-model', segments: groups, filledSegments: groups } }; },
  () => { const hundreds = 2 + Math.floor(random() * 7); const tens = Math.floor(random() * 10); const ones = Math.floor(random() * 10); const answer = hundreds * 100 + tens * 10 + ones; return { question: `${hundreds} hundreds, ${tens} tens, and ${ones} ones make what number?`, answer, options: wholeOptions(answer, random), operation: 'counting', context: 'counting', difficulty: 5, skill: 'place value to one thousand', explanation: `Use each digit's place value: ${hundreds * 100} + ${tens * 10} + ${ones} = ${answer}.`, visualModel: { kind: 'data-chart', labels: ['Hundreds', 'Tens', 'Ones'], values: [hundreds, tens, ones] } }; },
  () => { const number = 100 + Math.floor(random() * 800); const answer = Math.round(number / 10) * 10; return { question: `Round ${number} to the nearest ten.`, answer, options: options(answer, [Math.floor(number / 10) * 10, Math.ceil(number / 10) * 10, Math.round(number / 100) * 100, number, answer - 20, answer + 20], random), operation: 'counting', context: 'comparison', difficulty: 5, skill: 'rounding to the nearest ten', explanation: `The ones digit tells whether to use the lower or higher ten. ${number} rounds to ${answer}.`, visualModel: { kind: 'number-path', start: Math.floor(number / 10) * 10, end: Math.ceil(number / 10) * 10 } }; },
  () => { const left = 3; const right = 2; return { question: `Which comparison is true for 3/4 and 2/4?`, answer: '3/4 > 2/4', options: options('3/4 > 2/4', ['3/4 < 2/4', '3/4 = 2/4', 'They cannot be compared'], random), operation: 'fraction', context: 'fraction', difficulty: 5, skill: 'comparing fractions with equal denominators', explanation: `The pieces are the same size, and ${left} shaded fourths are greater than ${right} shaded fourths.`, visualModel: { kind: 'bar-model', segments: 4, filledSegments: 3 } }; },
  () => ({ question: 'Which fraction is equivalent to 1/2?', answer: '2/4', options: options('2/4', ['1/4', '3/4', '2/3'], random), operation: 'fraction', context: 'fraction', difficulty: 5, skill: 'equivalent fractions', explanation: 'Two of four equal parts cover the same amount as one of two equal parts.', visualModel: { kind: 'bar-model', segments: 4, filledSegments: 2 } }),
  () => { const width = 3 + Math.floor(random() * 6); const height = 2 + Math.floor(random() * 5); const answer = width * height; return { question: `What is the area of a ${width}-by-${height} rectangle?`, answer, options: wholeOptions(answer, random), operation: 'multiplication', context: 'geometry', difficulty: 5, skill: 'area of rectangles', explanation: `Area counts square units: ${width} x ${height} = ${answer} square units.`, visualModel: { kind: 'area-model', width, height } }; },
  () => { const width = 4 + Math.floor(random() * 6); const height = 2 + Math.floor(random() * 5); const answer = 2 * (width + height); return { question: `What is the perimeter of a rectangle ${width} units wide and ${height} units tall?`, answer, options: wholeOptions(answer, random), operation: 'addition', context: 'geometry', difficulty: 5, skill: 'perimeter of rectangles', explanation: `Add all four sides: ${width} + ${height} + ${width} + ${height} = ${answer}.`, visualModel: { kind: 'area-model', width, height } }; },
  () => { const minutes = [15, 20, 30, 45][Math.floor(random() * 4)]; return { question: `Practice starts at 3:00 and lasts ${minutes} minutes. When does it end?`, answer: `3:${String(minutes).padStart(2, '0')}`, options: options(`3:${String(minutes).padStart(2, '0')}`, ['3:10', '3:25', '3:40', '4:00'], random), operation: 'time', context: 'time', difficulty: 5, skill: 'elapsed time in minutes', explanation: `Count forward ${minutes} minutes from 3:00 to reach 3:${String(minutes).padStart(2, '0')}.`, visualModel: { kind: 'clock', hour: 3, minutes } }; },
  () => { const start = 30 + Math.floor(random() * 30); const added = 15 + Math.floor(random() * 20); const used = 5 + Math.floor(random() * 10); const answer = start + added - used; return { question: `A class has ${start} cards, makes ${added} more, then uses ${used}. How many remain?`, answer, options: wholeOptions(answer, random), operation: 'subtraction', context: 'word-problem', difficulty: 5, skill: 'two-step addition and subtraction', explanation: `First add to get ${start + added}. Then subtract ${used} to get ${answer}.`, visualModel: { kind: 'bar-model', segments: 3, filledSegments: 2 } }; },
  () => { const values = [4, 7, 5]; const answer = values[1] - values[0]; return { question: 'The chart shows 4 red, 7 blue, and 5 green votes. How many more blue than red?', answer, options: wholeOptions(answer, random), operation: 'subtraction', context: 'comparison', difficulty: 5, skill: 'interpreting bar graphs', explanation: `Compare blue and red: 7 - 4 = ${answer}.`, visualModel: { kind: 'data-chart', labels: ['Red', 'Blue', 'Green'], values } }; },
  () => ({ question: 'What kind of angle measures exactly 90 degrees?', answer: 'right angle', options: options('right angle', ['acute angle', 'obtuse angle', 'straight angle'], random), operation: 'geometry', context: 'geometry', difficulty: 5, skill: 'classifying angles', explanation: 'An angle measuring exactly 90 degrees is a right angle.', visualModel: { kind: 'angle', angleDegrees: 90 } }),
];

const gradeFour = (random: () => number): Factory[] => [
  () => { const a = 1200 + Math.floor(random() * 7000); const b = 500 + Math.floor(random() * 3000); const answer = a + b; return { question: `${a} + ${b} = ?`, answer, options: wholeOptions(answer, random), operation: 'addition', context: 'equation', difficulty: 6, skill: 'multi-digit addition', explanation: `Add ones, tens, hundreds, and thousands with regrouping to get ${answer}.`, visualModel: { kind: 'data-chart', labels: ['First', 'Second'], values: [a, b] } }; },
  () => { const a = 5000 + Math.floor(random() * 4000); const b = 1000 + Math.floor(random() * 3000); const answer = a - b; return { question: `${a} - ${b} = ?`, answer, options: wholeOptions(answer, random), operation: 'subtraction', context: 'equation', difficulty: 6, skill: 'multi-digit subtraction', explanation: `Subtract by place value and regroup when needed. The difference is ${answer}.`, visualModel: { kind: 'measurement', leftLength: a, rightLength: b } }; },
  () => { const a = 12 + Math.floor(random() * 78); const b = 3 + Math.floor(random() * 6); const answer = a * b; return { question: `${a} x ${b} = ?`, answer, options: wholeOptions(answer, random), operation: 'multiplication', context: 'equation', difficulty: 6, skill: 'two-digit by one-digit multiplication', explanation: `Break ${a} into tens and ones, multiply each part by ${b}, then combine to get ${answer}.`, visualModel: { kind: 'array', rows: b, columns: Math.min(10, Math.ceil(a / 10)) } }; },
  () => { const divisor = 4 + Math.floor(random() * 5); const quotient = 5 + Math.floor(random() * 8); const remainder = 1 + Math.floor(random() * (divisor - 1)); const total = divisor * quotient + remainder; const answer = `${quotient} R${remainder}`; return { question: `${total} divided by ${divisor} = ?`, answer, options: options(answer, [`${quotient}`, `${quotient + 1} R${remainder}`, `${quotient} R${remainder + 1}`], random), operation: 'division', context: 'equation', difficulty: 6, skill: 'division with remainders', explanation: `${divisor} x ${quotient} = ${divisor * quotient}, with ${remainder} left over.`, visualModel: { kind: 'bar-model', segments: divisor, filledSegments: divisor } }; },
  () => ({ question: 'Which number is a factor of 36?', answer: '9', options: options('9', ['5', '7', '11'], random), operation: 'multiplication', context: 'classification', difficulty: 6, skill: 'factors and factor pairs', explanation: '9 is a factor because 9 x 4 = 36 with no remainder.', visualModel: { kind: 'array', rows: 4, columns: 9 } }),
  () => ({ question: 'Which number is a multiple of 8?', answer: '40', options: options('40', ['34', '42', '46'], random), operation: 'multiplication', context: 'classification', difficulty: 6, skill: 'identifying multiples', explanation: '40 is a multiple of 8 because 8 x 5 = 40.', visualModel: { kind: 'number-path', start: 32, end: 40 } }),
  () => ({ question: 'Which fraction is equivalent to 3/4?', answer: '6/8', options: options('6/8', ['4/8', '5/8', '7/8'], random), operation: 'fraction', context: 'fraction', difficulty: 6, skill: 'generating equivalent fractions', explanation: 'Multiplying 3 and 4 by 2 gives the equivalent fraction 6/8.', visualModel: { kind: 'bar-model', segments: 8, filledSegments: 6 } }),
  () => ({ question: 'What is 2/8 + 3/8?', answer: '5/8', options: options('5/8', ['5/16', '1/8', '6/8'], random), operation: 'fraction', context: 'fraction', difficulty: 6, skill: 'adding fractions with equal denominators', explanation: 'Keep the denominator 8 and add the numerators: 2 + 3 = 5.', visualModel: { kind: 'bar-model', segments: 8, filledSegments: 5 } }),
  () => ({ question: 'Seven tenths is written as which decimal?', answer: '0.7', options: options('0.7', ['0.07', '7.0', '0.17'], random), operation: 'fraction', context: 'fraction', difficulty: 6, skill: 'decimal notation for tenths', explanation: 'Seven tenths means 7 in the tenths place, written 0.7.', visualModel: { kind: 'bar-model', segments: 10, filledSegments: 7 } }),
  () => ({ question: 'An angle measures 125 degrees. How is it classified?', answer: 'obtuse angle', options: options('obtuse angle', ['acute angle', 'right angle', 'straight angle'], random), operation: 'geometry', context: 'geometry', difficulty: 6, skill: 'measuring and classifying angles', explanation: '125 degrees is greater than 90 and less than 180, so it is obtuse.', visualModel: { kind: 'angle', angleDegrees: 125 } }),
  () => ({ question: 'How many centimeters are in 3 meters?', answer: 300, options: options(300, [30, 103, 3000], random), operation: 'counting', context: 'geometry', difficulty: 6, skill: 'metric length conversion', explanation: 'Each meter has 100 centimeters, so 3 x 100 = 300 centimeters.', visualModel: { kind: 'measurement', leftLength: 3, rightLength: 300 } }),
  () => { const boxes = 6; const perBox = 24; const given = 37; const answer = boxes * perBox - given; return { question: `${boxes} boxes hold ${perBox} books each. After ${given} books are given away, how many remain?`, answer, options: wholeOptions(answer, random), operation: 'subtraction', context: 'word-problem', difficulty: 6, skill: 'multi-step multiplication problems', explanation: `First find ${boxes} x ${perBox} = ${boxes * perBox}. Then subtract ${given} to get ${answer}.`, visualModel: { kind: 'bar-model', segments: boxes, filledSegments: boxes } }; },
];

const gradeFive = (random: () => number): Factory[] => [
  () => ({ question: 'What is 4.75 + 2.6?', answer: 7.35, options: options(7.35, [6.35, 7.25, 7.85], random), operation: 'addition', context: 'equation', difficulty: 7, skill: 'adding decimals to hundredths', explanation: 'Line up decimal points: 4.75 + 2.60 = 7.35.', visualModel: { kind: 'measurement', leftLength: 475, rightLength: 260 } }),
  () => ({ question: 'What is 8.2 - 3.47?', answer: 4.73, options: options(4.73, [4.63, 5.27, 5.73], random), operation: 'subtraction', context: 'equation', difficulty: 7, skill: 'subtracting decimals to hundredths', explanation: 'Write 8.2 as 8.20, line up decimal points, and subtract to get 4.73.', visualModel: { kind: 'measurement', leftLength: 820, rightLength: 347 } }),
  () => ({ question: 'What is 1/2 + 1/3?', answer: '5/6', options: options('5/6', ['2/5', '2/6', '1/5'], random), operation: 'fraction', context: 'fraction', difficulty: 7, skill: 'adding fractions with unlike denominators', explanation: 'Use sixths: 1/2 = 3/6 and 1/3 = 2/6. Then 3/6 + 2/6 = 5/6.', visualModel: { kind: 'bar-model', segments: 6, filledSegments: 5 } }),
  () => ({ question: 'What is 2/3 of 3/4?', answer: '1/2', options: options('1/2', ['2/7', '5/7', '5/12'], random), operation: 'fraction', context: 'fraction', difficulty: 7, skill: 'multiplying fractions', explanation: 'Multiply 2 x 3 and 3 x 4 to get 6/12, then simplify to 1/2.', visualModel: { kind: 'bar-model', segments: 12, filledSegments: 6 } }),
  () => { const width = 5; const height = 3; const depth = 4; const answer = width * height * depth; return { question: `A rectangular prism is ${width} by ${height} by ${depth}. What is its volume?`, answer, options: wholeOptions(answer, random), operation: 'multiplication', context: 'geometry', difficulty: 7, skill: 'volume of rectangular prisms', explanation: `Volume = length x width x height: ${width} x ${height} x ${depth} = ${answer} cubic units.`, visualModel: { kind: 'area-model', width, height } }; },
  () => ({ question: 'Which ordered pair names the plotted point?', answer: '(4, 3)', options: options('(4, 3)', ['(3, 4)', '(4, 2)', '(3, 3)'], random), operation: 'spatial', context: 'spatial', difficulty: 7, skill: 'graphing ordered pairs', explanation: 'Move 4 units right on the x-axis and 3 units up on the y-axis, giving (4, 3).', visualModel: { kind: 'coordinate', pointX: 4, pointY: 3 } }),
  () => ({ question: 'Evaluate 6 + 3 x 4.', answer: 18, options: options(18, [36, 24, 15], random), operation: 'multiplication', context: 'equation', difficulty: 7, skill: 'order of operations', explanation: 'Multiply before adding: 3 x 4 = 12, then 6 + 12 = 18.', visualModel: { kind: 'bar-model', segments: 4, filledSegments: 3 } }),
  () => ({ question: 'What happens to 4.36 when it is multiplied by 100?', answer: 436, options: options(436, [43.6, 4.36, 4360], random), operation: 'multiplication', context: 'equation', difficulty: 7, skill: 'powers of ten and place value', explanation: 'Multiplying by 100 shifts every digit two places left, so 4.36 becomes 436.', visualModel: { kind: 'data-chart', labels: ['Ones', 'Tenths', 'Hundredths'], values: [4, 3, 6] } }),
  () => ({ question: 'How many milliliters are in 2.5 liters?', answer: 2500, options: options(2500, [250, 2050, 25000], random), operation: 'counting', context: 'geometry', difficulty: 7, skill: 'metric capacity conversion', explanation: 'One liter equals 1,000 milliliters, so 2.5 x 1,000 = 2,500 milliliters.', visualModel: { kind: 'measurement', leftLength: 25, rightLength: 100 } }),
  () => ({ question: 'A line plot shows lengths 1/2, 3/4, 3/4, and 1. What is the most frequent length?', answer: '3/4', options: options('3/4', ['1/2', '1', '2/4'], random), operation: 'comparison', context: 'comparison', difficulty: 7, skill: 'interpreting fraction data', explanation: '3/4 appears twice, more often than any other length, so it is the most frequent.', visualModel: { kind: 'data-chart', labels: ['1/2', '3/4', '1'], values: [1, 2, 1] } }),
  () => ({ question: 'Which statement is always true?', answer: 'Every square is a rectangle', options: options('Every square is a rectangle', ['Every rectangle is a square', 'Every triangle is a quadrilateral', 'Every rhombus has right angles'], random), operation: 'geometry', context: 'classification', difficulty: 7, skill: 'classifying quadrilaterals in a hierarchy', explanation: 'A square has four right angles, so it meets every requirement for a rectangle.', visualModel: { kind: 'shape', shape: 'square', color: 'blue' } }),
  () => { const total = 275; const groups = 8; const full = Math.floor(total / groups); const remainder = total % groups; const answer = `${full} R${remainder}`; return { question: `${total} supplies are packed equally into ${groups} bins. How many go in each bin, and how many remain?`, answer, options: options(answer, ['34 R2', '35 R3', '33 R5'], random), operation: 'division', context: 'word-problem', difficulty: 7, skill: 'multi-digit division with interpretation', explanation: `${groups} x ${full} = ${groups * full}, leaving ${remainder}. Each bin gets ${full} with ${remainder} remaining.`, visualModel: { kind: 'bar-model', segments: groups, filledSegments: groups } }; },
];

export const generateUpperElementaryMathProblem = (level: UpperElementaryMathLevel, step: number): MathProblem => {
  const random = createSeededRandom(getDailySeed(`upper-elementary-math-grade-${level}`, step));
  const factories = level === 5 ? gradeThree(random) : level === 6 ? gradeFour(random) : gradeFive(random);
  const problem = factories[step % factories.length]();
  return { ...problem, question: `${PHASES[step % PHASES.length]}: ${problem.question}` };
};
