import { createSeededRandom, getDailySeed } from '../dailyRotation';
import { EarlySpeechQuestion, EarlySpeechVisual } from './earlySpeech';

export type UpperElementarySpeechLevel = 5 | 6 | 7;
const PHASES = ['Listen and notice', 'Teacher model', 'Try it together', 'Speak with confidence', 'Review and remember', 'Show what you know'];
const shuffle = <T,>(items: T[], random: () => number): T[] => { const copy = [...items]; for (let index = copy.length - 1; index > 0; index -= 1) { const swap = Math.floor(random() * (index + 1)); [copy[index], copy[swap]] = [copy[swap], copy[index]]; } return copy; };
const q = (prompt: string, focusText: string, answer: string, distractors: string[], skill: string, coachCue: string, explanation: string, random: () => number, visual: EarlySpeechVisual = 'conversation'): Omit<EarlySpeechQuestion, 'id' | 'phase'> => ({ prompt, focusText, answer, options: shuffle([answer, ...distractors.slice(0, 3)], random), skill, coachCue, explanation, visual });

const gradeThree = (random: () => number) => [
  q('Which response follows discussion rules?', 'Maya is speaking about the class garden.', 'Listen, then connect your idea when Maya finishes.', ['Interrupt with a new topic.', 'Speak louder than Maya.', 'Ignore Maya and repeat yourself.'], 'discussion turn-taking and preparation', 'Listen for the speaker’s complete idea before entering the discussion.', 'Waiting and connecting to Maya’s idea keeps the discussion respectful and focused.', random),
  q('Which statement accurately paraphrases the speaker?', 'Speaker: Wetlands absorb extra rain and reduce flooding.', 'Wetlands can hold rainwater, which helps limit floods.', ['Wetlands cause every flood.', 'Rain cannot enter wetlands.', 'The speaker only described animals.'], 'paraphrasing spoken information', 'Keep the original meaning but restate it in your own words.', 'The answer preserves both key ideas: holding extra rainwater and reducing floods.', random, 'listening'),
  q('Which follow-up question deepens the conversation?', 'Partner: Our paper bridge held more weight after we folded it.', 'Why do you think the folds made it stronger?', ['Was the paper blue?', 'Can we stop talking?', 'Did you use a table?'], 'asking relevant follow-up questions', 'Ask about the reason, evidence, or process behind the idea.', 'The why question invites the partner to explain the design reasoning.', random, 'question'),
  q('Which response supports a claim with evidence?', 'Claim: The second filter worked better.', 'The second filter worked better because the water looked clearer after the test.', ['I just like the second filter.', 'Filters are interesting.', 'The cups were on a table.'], 'speaking with relevant evidence', 'State the claim, then connect a specific observation using because.', 'The response links the claim to the observed result from the test.', random),
  q('Which presentation order is clearest?', 'Topic: how a seed becomes a plant', 'Introduce the topic, explain steps in order, then summarize.', ['Give the ending, change topics, then begin.', 'List details with no introduction.', 'Repeat one fact six times.'], 'organizing an oral presentation', 'Give listeners a beginning, an organized middle, and a clear ending.', 'The sequence previews the topic, explains it logically, and closes with the main idea.', random, 'sequence'),
  q('How should a speaker present an important safety direction?', 'Wear goggles before beginning the experiment.', 'Use a clear volume, steady pace, and emphasis on wear goggles.', ['Whisper as quickly as possible.', 'Look away and skip words.', 'Use the same flat tone for everything.'], 'volume pace and emphasis', 'Slow slightly and emphasize the words the listener must remember.', 'Clear volume, pacing, and emphasis make the safety action easier to understand.', random),
  q('Which sentence uses language appropriate for a class presentation?', 'Explaining the results to the class', 'Our evidence suggests that sunlight increased growth.', ['Sunlight was, like, totally doing stuff.', 'You know, the plant thing happened.', 'Whatever, it grew.'], 'formal and informal language', 'Choose precise words and complete sentences for a formal audience.', 'The response uses precise academic language suitable for presenting findings.', random, 'sentence'),
  q('Which sentence has correct subject-verb agreement?', 'Choose the sentence that sounds correct.', 'The group of students is ready.', ['The group of students are ready.', 'The group be ready.', 'The students is ready.'], 'subject verb agreement in speech', 'Find the main subject before choosing the verb.', 'Group is the singular subject, so it correctly pairs with is.', random, 'sentence'),
  q('Which sentence clearly shows cause and effect?', 'Rain fell all night. The field became muddy.', 'Because rain fell all night, the field became muddy.', ['Rain and the field.', 'The muddy because night.', 'Although the field.'], 'complex sentences with conjunctions', 'Use a conjunction that shows how the two complete ideas connect.', 'Because clearly links the overnight rain as the cause of the muddy field.', random, 'sentence'),
  q('Which summary captures the speaker’s main point?', 'Speaker: Bees carry pollen, helping flowers produce seeds.', 'Bees help flowering plants reproduce by moving pollen.', ['Bees have wings.', 'All seeds are carried by bees.', 'Flowers do not need pollen.'], 'listening and oral summarizing', 'Keep the central relationship and leave out unrelated details.', 'The summary combines the bee action and its important result for plants.', random, 'listening'),
  q('What should you say when one direction is unclear?', 'Teacher: Record the result after calibrating the scale.', 'Could you explain what calibrating the scale means?', ['I will skip that step.', 'The scale is wrong.', 'Please repeat every lesson from yesterday.'], 'specific clarification questions', 'Name the exact word or step that needs clarification.', 'The question politely identifies calibrating as the precise unclear idea.', random, 'question'),
  q('Which response compares two ideas clearly?', 'A rain barrel stores water. A drain moves water away.', 'Both manage rainwater, but one stores it while the other moves it.', ['They are both things.', 'Only the words are different.', 'Rain barrels and drains are identical.'], 'oral compare and contrast', 'State one similarity and one meaningful difference.', 'The response accurately compares the shared purpose and different actions.', random, 'category'),
];

const gradeFour = (random: () => number) => [
  q('Which response connects two speakers’ ideas?', 'Ava: Trees cool sidewalks. Ben: Trees also absorb rain.', 'Ava and Ben show that trees help cities with both heat and water.', ['Only Ava has an idea.', 'Trees are green.', 'The speakers disagree about everything.'], 'synthesizing discussion ideas', 'Name both contributions and explain their shared larger idea.', 'The response combines cooling and rain absorption into one conclusion about city benefits.', random),
  q('Which statement cites the speaker’s evidence accurately?', 'Speaker: The shaded surface was 11 degrees cooler.', 'The measurement showed the shaded surface was 11 degrees cooler.', ['Shade always fixes every problem.', 'The speaker liked trees.', 'Temperatures are numbers.'], 'citing oral evidence', 'Repeat the exact measurement that supports the conclusion.', 'The answer accurately reports the relevant measured difference without exaggerating it.', random, 'listening'),
  q('Which response builds on a partner’s idea?', 'Partner: Wider bases made our towers steadier.', 'I agree, and we could test three base widths to find the most stable one.', ['Let us discuss lunch instead.', 'Your idea is over.', 'Towers are tall.'], 'building on ideas in collaboration', 'Refer to the partner’s idea, then add a connected next step.', 'The response acknowledges the idea and extends it into a useful investigation.', random),
  q('Which is the best oral summary?', 'The speaker describes evaporation, condensation, and precipitation.', 'Water moves through a cycle of evaporation, condensation, and precipitation.', ['Rain is wet.', 'Evaporation is the only step.', 'The speaker used three long words.'], 'summarizing presented information', 'State the central process and include only its essential parts.', 'The answer names the water cycle and concisely includes all three essential stages.', random, 'listening'),
  q('Which transition best moves from evidence to conclusion?', 'Evidence: three trials produced the same result.', 'Because all three trials agreed, we conclude the pattern is reliable.', ['Now for an unrelated story.', 'That is a number.', 'Before we began, goodbye.'], 'presentation transitions', 'Use a transition that tells listeners how evidence supports the conclusion.', 'Because explicitly connects the repeated trial results to the conclusion.', random, 'sequence'),
  q('Which argument gives a claim, reason, and evidence?', 'Should the school add refill stations?', 'The school should add refill stations because they reduce waste; our audit found 120 plastic bottles in one day.', ['Refill stations are nice.', 'I saw a bottle once.', 'Everyone must agree with me.'], 'oral argument with reasons and evidence', 'State the claim, explain why, and include specific evidence.', 'The response contains a clear proposal, a relevant reason, and measured evidence.', random),
  q('What tone fits a presentation about emergency preparation?', 'Audience: families learning a safety plan', 'calm, clear, and serious', ['silly and rushed', 'angry and confusing', 'whispered and uncertain'], 'matching tone to purpose', 'Match voice, pace, and emotion to the topic and audience.', 'A calm, clear, serious tone helps families understand and remember safety information.', random),
  q('Which sentence uses formal English?', 'Reporting a science conclusion', 'The results indicate that the material absorbed the most water.', ['The stuff soaked up a bunch.', 'It was kinda the best.', 'That thing did lots.'], 'formal language for academic speaking', 'Replace vague conversational words with precise academic language.', 'The sentence uses specific vocabulary and a complete structure appropriate for school reporting.', random, 'sentence'),
  q('Which sentence uses a relative pronoun correctly?', 'Combine: The engineer designed the bridge. She visited our class.', 'The engineer who designed the bridge visited our class.', ['The engineer which she designed visited.', 'Who the bridge engineer.', 'The engineer where designed it.'], 'relative pronouns in speaking', 'Use who to add information about a person.', 'Who correctly introduces the clause describing the engineer.', random, 'sentence'),
  q('Which sentence uses a modal auxiliary to show possibility?', 'The clouds are dark.', 'It might rain this afternoon.', ['It rained yesterday.', 'Rain is water.', 'The cloud rains always.'], 'modal auxiliaries', 'Words such as might, may, and could show possibility.', 'Might correctly signals that rain is possible but not certain.', random, 'sentence'),
  q('How can a speaker clarify the meaning of conduct?', 'Sentence: Scientists conduct an experiment.', 'Explain that conduct means carry out or perform.', ['Say it only means behavior.', 'Skip the sentence.', 'Replace it with a random word.'], 'clarifying multiple-meaning words', 'Use the sentence context to select and explain the intended meaning.', 'In this context, conduct is a verb meaning to carry out an experiment.', random, 'question'),
  q('Which disagreement is respectful and evidence-based?', 'Partner: The first design was strongest.', 'I see it differently because the chart shows the second design held more weight.', ['You are completely wrong.', 'Stop talking about designs.', 'I disagree because I said so.'], 'respectful evidence-based disagreement', 'Acknowledge the idea, state your position, and cite evidence.', 'The response disagrees respectfully and supports the difference with chart evidence.', random),
];

const gradeFive = (random: () => number) => [
  q('Which action helps a group fulfill discussion roles?', 'Facilitator, evidence finder, recorder, reporter', 'Each person completes the assigned role and shares results.', ['One person does every task.', 'The group skips the evidence.', 'Everyone speaks at once.'], 'collaborative discussion roles', 'Use each role to distribute thinking and keep the group accountable.', 'Completing and sharing each role ensures that the group uses evidence and hears every contribution.', random),
  q('Which statement synthesizes the comments?', 'Lena: Solar panels reduce electricity use. Omar: They cost money to install.', 'Solar panels may lower energy use, but the school must consider installation cost.', ['Only cost matters.', 'The comments are unrelated.', 'Solar panels have no tradeoffs.'], 'synthesizing multiple perspectives', 'Combine both perspectives without erasing their important difference.', 'The response integrates the potential benefit and the financial concern.', random),
  q('Which question probes a speaker’s reasoning?', 'Speaker: This route is the safest.', 'What evidence did you use to compare the route risks?', ['What color is the map?', 'Do you like walking?', 'Can we choose quickly?'], 'probing reasoning with questions', 'Ask how the claim was developed and what evidence supports it.', 'The question invites the speaker to explain the comparison and evidence behind the claim.', random, 'question'),
  q('Which oral citation is clearest?', 'Source: city water report, 2025', 'According to the 2025 city water report, household use fell by 8 percent.', ['I heard a number somewhere.', 'A report says stuff changed.', 'Everyone knows water use fell.'], 'citing sources in speech', 'Name the source and state the exact information it provides.', 'The sentence identifies the source, date, measure, and result clearly.', random),
  q('Which response evaluates an argument fairly?', 'Claim: Add bike racks. Evidence: 42 students bike to school.', 'The evidence is relevant, but we also need to know current rack capacity.', ['The claim must be perfect.', 'Numbers are never evidence.', 'Bike racks solve every transportation problem.'], 'evaluating claims and evidence', 'Judge what the evidence supports and identify important missing information.', 'The response recognizes relevant evidence while naming a reasonable information gap.', random),
  q('Which structure best fits a five-minute explanatory speech?', 'Topic: how erosion changes a shoreline', 'Hook, clear claim, organized evidence, explanation, conclusion', ['Five unrelated facts.', 'Conclusion first and no evidence.', 'Repeat the hook for five minutes.'], 'structuring formal presentations', 'Organize the speech so listeners can follow the claim and evidence.', 'The structure introduces the topic, develops evidence logically, and closes clearly.', random, 'sequence'),
  q('Which visual would best support a speech about population change?', 'Comparing population across five years', 'A labeled line graph showing all five years', ['A decorative cartoon', 'An unlabeled color square', 'A photo of an unrelated city'], 'selecting relevant multimedia', 'Choose media that makes the exact relationship easier to understand.', 'A labeled line graph directly shows change across time and supports comparison.', random),
  q('Which delivery creates a persuasive but respectful tone?', 'Proposal: create a quiet reading area', 'Use confident pacing, specific benefits, and respectful language.', ['Shout at anyone who disagrees.', 'Rush through the evidence.', 'Use insults instead of reasons.'], 'persuasive delivery and tone', 'Confidence comes from clear reasons and controlled delivery, not pressure.', 'Steady delivery and respectful evidence make the proposal persuasive without dismissing listeners.', random),
  q('Which sentence fits a formal school-board audience?', 'Requesting support for a garden program', 'The program would provide hands-on science learning and fresh produce.', ['The garden would be super cool.', 'You guys should totally do it.', 'Plants are awesome and stuff.'], 'adapting register to audience', 'Use precise vocabulary and complete sentences for a formal audience.', 'The response states concrete benefits in language appropriate for decision-makers.', random, 'sentence'),
  q('Which sentence uses the present perfect tense correctly?', 'The team began testing last week and continues now.', 'The team has tested four designs.', ['The team have test four designs.', 'The team testing yesterday.', 'The team has test four designs.'], 'perfect verb tenses', 'Use has or have with the past participle to connect past action to now.', 'Has tested correctly forms the present perfect tense for the singular team.', random, 'sentence'),
  q('Which sentence uses correlative conjunctions correctly?', 'Both evidence and explanation matter.', 'Both the data and the explanation support the claim.', ['Both the data or the explanation.', 'Either data and explanation.', 'Neither evidence or reasons.'], 'correlative conjunctions', 'Use matched pairs such as both-and, either-or, and neither-nor.', 'Both and and work as a matched pair connecting two equal supports.', random, 'sentence'),
  q('How should the same science idea change for younger students?', 'Original: Photosynthesis converts light energy into chemical energy.', 'Use familiar words, a plant example, and a simple diagram.', ['Use more unexplained technical terms.', 'Speak faster.', 'Remove every example.'], 'adapting speech to audience', 'Keep the science accurate while adjusting vocabulary and examples.', 'Familiar language and a concrete diagram make the accurate idea accessible to younger listeners.', random),
];

export const getUpperElementarySpeechQuestionBank = (level: UpperElementarySpeechLevel): EarlySpeechQuestion[] => {
  const random = createSeededRandom(`voice-cache-upper-speech-${level}`);
  const bank = level === 5 ? gradeThree(random) : level === 6 ? gradeFour(random) : gradeFive(random);
  return bank.map((question, index) => ({
    ...question,
    id: `upper-speech-bank-${level}-${index}-${question.skill.replace(/[^a-z0-9]+/gi, '-').toLowerCase()}`,
    phase: PHASES[index % PHASES.length],
  }));
};

export const generateUpperElementarySpeechQuestion = (level: UpperElementarySpeechLevel, step: number): EarlySpeechQuestion => {
  const random = createSeededRandom(getDailySeed(`upper-elementary-speech-grade-${level}`, step));
  const bank = level === 5 ? gradeThree(random) : level === 6 ? gradeFour(random) : gradeFive(random);
  const question = bank[step % bank.length];
  return { ...question, id: `upper-speech-${level}-${step}-${question.skill.replace(/[^a-z0-9]+/gi, '-').toLowerCase()}`, phase: PHASES[step % PHASES.length] };
};
